//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.08 at 07:56:29 PM IST 
//


package com.ge.icfp.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.wff.core.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="New_Lender_or_Borrower_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PandL_Amt" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Orig_LegalAgreement_Attached_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "newLenderOrBorrowerFlag",
    "pandLAmt",
    "origLegalAgreementAttachedFlag"
})
@XmlRootElement(name = "Assignment", namespace = "http://treasury.ge.com/schemas/ICFP/Assignment.xsd")
public class Assignment
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "New_Lender_or_Borrower_Flag", namespace = "http://treasury.ge.com/schemas/ICFP/Assignment.xsd")
    protected Boolean newLenderOrBorrowerFlag;
    @XmlElement(name = "PandL_Amt", namespace = "http://treasury.ge.com/schemas/ICFP/Assignment.xsd")
    protected Double pandLAmt;
    @XmlElement(name = "Orig_LegalAgreement_Attached_Flag", namespace = "http://treasury.ge.com/schemas/ICFP/Assignment.xsd")
    protected Boolean origLegalAgreementAttachedFlag;

    /**
     * Gets the value of the newLenderOrBorrowerFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNewLenderOrBorrowerFlag() {
        return newLenderOrBorrowerFlag;
    }

    /**
     * Sets the value of the newLenderOrBorrowerFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewLenderOrBorrowerFlag(Boolean value) {
        this.newLenderOrBorrowerFlag = value;
    }

    /**
     * Gets the value of the pandLAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPandLAmt() {
        return pandLAmt;
    }

    /**
     * Sets the value of the pandLAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPandLAmt(Double value) {
        this.pandLAmt = value;
    }

    /**
     * Gets the value of the origLegalAgreementAttachedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOrigLegalAgreementAttachedFlag() {
        return origLegalAgreementAttachedFlag;
    }

    /**
     * Sets the value of the origLegalAgreementAttachedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrigLegalAgreementAttachedFlag(Boolean value) {
        this.origLegalAgreementAttachedFlag = value;
    }

    public Assignment withNewLenderOrBorrowerFlag(Boolean value) {
        setNewLenderOrBorrowerFlag(value);
        return this;
    }

    public Assignment withPandLAmt(Double value) {
        setPandLAmt(value);
        return this;
    }

    public Assignment withOrigLegalAgreementAttachedFlag(Boolean value) {
        setOrigLegalAgreementAttachedFlag(value);
        return this;
    }

}
