//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.08 at 07:56:29 PM IST 
//


package com.ge.icfp.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.wff.core.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SSO_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Assigner_Sso_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Assigner_First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Assigner_Last_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Op_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "group",
    "ssoid",
    "firstName",
    "lastName",
    "assignerSsoId",
    "assignerFirstName",
    "assignerLastName",
    "opCode"
})
@XmlRootElement(name = "Business_Approvers", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
public class BusinessApprovers
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Group", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String group;
    @XmlElement(name = "SSO_ID", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String ssoid;
    @XmlElement(name = "First_Name", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String firstName;
    @XmlElement(name = "Last_Name", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String lastName;
    @XmlElement(name = "Assigner_Sso_Id", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String assignerSsoId;
    @XmlElement(name = "Assigner_First_Name", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String assignerFirstName;
    @XmlElement(name = "Assigner_Last_name", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String assignerLastName;
    @XmlElement(name = "Op_Code", namespace = "http://treasury.ge.com/schemas/ICFP/BusinessApprovers.xsd")
    protected String opCode;

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the ssoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSOID() {
        return ssoid;
    }

    /**
     * Sets the value of the ssoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSOID(String value) {
        this.ssoid = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the assignerSsoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignerSsoId() {
        return assignerSsoId;
    }

    /**
     * Sets the value of the assignerSsoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignerSsoId(String value) {
        this.assignerSsoId = value;
    }

    /**
     * Gets the value of the assignerFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignerFirstName() {
        return assignerFirstName;
    }

    /**
     * Sets the value of the assignerFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignerFirstName(String value) {
        this.assignerFirstName = value;
    }

    /**
     * Gets the value of the assignerLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignerLastName() {
        return assignerLastName;
    }

    /**
     * Sets the value of the assignerLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignerLastName(String value) {
        this.assignerLastName = value;
    }

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    public BusinessApprovers withGroup(String value) {
        setGroup(value);
        return this;
    }

    public BusinessApprovers withSSOID(String value) {
        setSSOID(value);
        return this;
    }

    public BusinessApprovers withFirstName(String value) {
        setFirstName(value);
        return this;
    }

    public BusinessApprovers withLastName(String value) {
        setLastName(value);
        return this;
    }

    public BusinessApprovers withAssignerSsoId(String value) {
        setAssignerSsoId(value);
        return this;
    }

    public BusinessApprovers withAssignerFirstName(String value) {
        setAssignerFirstName(value);
        return this;
    }

    public BusinessApprovers withAssignerLastName(String value) {
        setAssignerLastName(value);
        return this;
    }

    public BusinessApprovers withOpCode(String value) {
        setOpCode(value);
        return this;
    }

}
