//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.08 at 07:56:29 PM IST 
//


package com.ge.icfp.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.wff.core.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://treasury.ge.com/ErrorLookup.xsd}ErrorLookup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorLookups"
})
@XmlRootElement(name = "Error", namespace = "http://treasury.ge.com/ErrorLookup.xsd")
public class Error
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ErrorLookup", namespace = "http://treasury.ge.com/ErrorLookup.xsd")
    protected List<ErrorLookup> errorLookups;

    /**
     * Gets the value of the errorLookups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorLookups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorLookups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorLookup }
     * 
     * 
     */
    public List<ErrorLookup> getErrorLookups() {
        if (errorLookups == null) {
            errorLookups = new ArrayList<ErrorLookup>();
        }
        return this.errorLookups;
    }

    public Error withErrorLookups(ErrorLookup... values) {
        if (values!= null) {
            for (ErrorLookup value: values) {
                getErrorLookups().add(value);
            }
        }
        return this;
    }

    public Error withErrorLookups(Collection<ErrorLookup> values) {
        if (values!= null) {
            getErrorLookups().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the errorLookups property.
     * 
     * @param errorLookups
     *     allowed object is
     *     {@link ErrorLookup }
     *     
     */
    public void setErrorLookups(List<ErrorLookup> errorLookups) {
        this.errorLookups = errorLookups;
    }

}
