//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 12:57:11 AM IST 
//


package com.ge.icfp.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.wff.core.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Deal_Seq_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Wf_Stage_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Action_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SSO_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dealSeqId",
    "wfStageId",
    "actionId",
    "ssoId",
    "name",
    "dateTime"
})
@XmlRootElement(name = "User_Action_Data", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
public class UserActionData
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Deal_Seq_Id", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
    protected Integer dealSeqId;
    @XmlElement(name = "Wf_Stage_Id", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
    protected Integer wfStageId;
    @XmlElement(name = "Action_Id", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
    protected Integer actionId;
    @XmlElement(name = "SSO_Id", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
    protected String ssoId;
    @XmlElement(name = "Name", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
    protected String name;
    @XmlElement(name = "DateTime", namespace = "http://treasury.ge.com/schemas/ICFP/UserMgmt.xsd")
    protected String dateTime;

    /**
     * Gets the value of the dealSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDealSeqId() {
        return dealSeqId;
    }

    /**
     * Sets the value of the dealSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDealSeqId(Integer value) {
        this.dealSeqId = value;
    }

    /**
     * Gets the value of the wfStageId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWfStageId() {
        return wfStageId;
    }

    /**
     * Sets the value of the wfStageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWfStageId(Integer value) {
        this.wfStageId = value;
    }

    /**
     * Gets the value of the actionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * Sets the value of the actionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActionId(Integer value) {
        this.actionId = value;
    }

    /**
     * Gets the value of the ssoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSOId() {
        return ssoId;
    }

    /**
     * Sets the value of the ssoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSOId(String value) {
        this.ssoId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    public UserActionData withDealSeqId(Integer value) {
        setDealSeqId(value);
        return this;
    }

    public UserActionData withWfStageId(Integer value) {
        setWfStageId(value);
        return this;
    }

    public UserActionData withActionId(Integer value) {
        setActionId(value);
        return this;
    }

    public UserActionData withSSOId(String value) {
        setSSOId(value);
        return this;
    }

    public UserActionData withName(String value) {
        setName(value);
        return this;
    }

    public UserActionData withDateTime(String value) {
        setDateTime(value);
        return this;
    }

}
