//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.hydus.hwf.jaxb.adapters.XMLDatetimeAsCalendarAdapter;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Site_Id" type="{http://www.w3.org/2001/XMLSchema}integer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ALOC_Record_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ALOC_Record_Number" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Site_Prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Bank_Reference_Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Applicant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Beneficiary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BUC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Instrument_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Instrument_Amount_From" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Instrument_Amount_To" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Payment_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Payment_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Payment_Date_From" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Payment_Date_To" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Instrument_Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Foreign_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Payment_Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Payment_Bank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Country_Of_Issuence" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Payment_Currencies" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siteIds",
    "alocRecordId",
    "alocRecordNumber",
    "sitePrefix",
    "bankReferenceNumber",
    "applicant",
    "beneficiary",
    "buc",
    "adn",
    "instrumentAmount",
    "instrumentAmountFrom",
    "instrumentAmountTo",
    "paymentAmount",
    "paymentDate",
    "paymentDateFrom",
    "paymentDateTo",
    "instrumentCurrency",
    "foreignExpiryDate",
    "paymentCurrency",
    "paymentBank",
    "countryOfIssuences",
    "paymentCurrencies"
})
@XmlRootElement(name = "APMSearch", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
public class APMSearch
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Site_Id", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected List<BigInteger> siteIds;
    @XmlElement(name = "ALOC_Record_Id", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String alocRecordId;
    @XmlElement(name = "ALOC_Record_Number", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected BigInteger alocRecordNumber;
    @XmlElement(name = "Site_Prefix", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String sitePrefix;
    @XmlElement(name = "Bank_Reference_Number", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String bankReferenceNumber;
    @XmlElement(name = "Applicant", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String applicant;
    @XmlElement(name = "Beneficiary", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String beneficiary;
    @XmlElement(name = "BUC", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String buc;
    @XmlElement(name = "ADN", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String adn;
    @XmlElement(name = "Instrument_Amount", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected BigDecimal instrumentAmount;
    @XmlElement(name = "Instrument_Amount_From", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected BigDecimal instrumentAmountFrom;
    @XmlElement(name = "Instrument_Amount_To", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected BigDecimal instrumentAmountTo;
    @XmlElement(name = "Payment_Amount", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected BigDecimal paymentAmount;
    @XmlElement(name = "Payment_Date", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar paymentDate;
    @XmlElement(name = "Payment_Date_From", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar paymentDateFrom;
    @XmlElement(name = "Payment_Date_To", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar paymentDateTo;
    @XmlElement(name = "Instrument_Currency", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String instrumentCurrency;
    @XmlElement(name = "Foreign_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar foreignExpiryDate;
    @XmlElement(name = "Payment_Currency", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String paymentCurrency;
    @XmlElement(name = "Payment_Bank", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected String paymentBank;
    @XmlElement(name = "Country_Of_Issuence", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected List<String> countryOfIssuences;
    @XmlElement(name = "Payment_Currencies", namespace = "http://treasury.ge.com/schemas/ALOC/APM/APMSearch.xsd")
    protected List<String> paymentCurrencies;

    /**
     * Gets the value of the siteIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiteIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getSiteIds() {
        if (siteIds == null) {
            siteIds = new ArrayList<BigInteger>();
        }
        return this.siteIds;
    }

    /**
     * Gets the value of the alocRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALOCRecordId() {
        return alocRecordId;
    }

    /**
     * Sets the value of the alocRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALOCRecordId(String value) {
        this.alocRecordId = value;
    }

    /**
     * Gets the value of the alocRecordNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getALOCRecordNumber() {
        return alocRecordNumber;
    }

    /**
     * Sets the value of the alocRecordNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setALOCRecordNumber(BigInteger value) {
        this.alocRecordNumber = value;
    }

    /**
     * Gets the value of the sitePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitePrefix() {
        return sitePrefix;
    }

    /**
     * Sets the value of the sitePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitePrefix(String value) {
        this.sitePrefix = value;
    }

    /**
     * Gets the value of the bankReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankReferenceNumber() {
        return bankReferenceNumber;
    }

    /**
     * Sets the value of the bankReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankReferenceNumber(String value) {
        this.bankReferenceNumber = value;
    }

    /**
     * Gets the value of the applicant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * Sets the value of the applicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicant(String value) {
        this.applicant = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiary(String value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the buc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUC() {
        return buc;
    }

    /**
     * Sets the value of the buc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUC(String value) {
        this.buc = value;
    }

    /**
     * Gets the value of the adn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADN() {
        return adn;
    }

    /**
     * Sets the value of the adn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADN(String value) {
        this.adn = value;
    }

    /**
     * Gets the value of the instrumentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrumentAmount() {
        return instrumentAmount;
    }

    /**
     * Sets the value of the instrumentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrumentAmount(BigDecimal value) {
        this.instrumentAmount = value;
    }

    /**
     * Gets the value of the instrumentAmountFrom property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrumentAmountFrom() {
        return instrumentAmountFrom;
    }

    /**
     * Sets the value of the instrumentAmountFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrumentAmountFrom(BigDecimal value) {
        this.instrumentAmountFrom = value;
    }

    /**
     * Gets the value of the instrumentAmountTo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrumentAmountTo() {
        return instrumentAmountTo;
    }

    /**
     * Sets the value of the instrumentAmountTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrumentAmountTo(BigDecimal value) {
        this.instrumentAmountTo = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentAmount(BigDecimal value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDate(Calendar value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the paymentDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPaymentDateFrom() {
        return paymentDateFrom;
    }

    /**
     * Sets the value of the paymentDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDateFrom(Calendar value) {
        this.paymentDateFrom = value;
    }

    /**
     * Gets the value of the paymentDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPaymentDateTo() {
        return paymentDateTo;
    }

    /**
     * Sets the value of the paymentDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDateTo(Calendar value) {
        this.paymentDateTo = value;
    }

    /**
     * Gets the value of the instrumentCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentCurrency() {
        return instrumentCurrency;
    }

    /**
     * Sets the value of the instrumentCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentCurrency(String value) {
        this.instrumentCurrency = value;
    }

    /**
     * Gets the value of the foreignExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getForeignExpiryDate() {
        return foreignExpiryDate;
    }

    /**
     * Sets the value of the foreignExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignExpiryDate(Calendar value) {
        this.foreignExpiryDate = value;
    }

    /**
     * Gets the value of the paymentCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCurrency() {
        return paymentCurrency;
    }

    /**
     * Sets the value of the paymentCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCurrency(String value) {
        this.paymentCurrency = value;
    }

    /**
     * Gets the value of the paymentBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentBank() {
        return paymentBank;
    }

    /**
     * Sets the value of the paymentBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentBank(String value) {
        this.paymentBank = value;
    }

    /**
     * Gets the value of the countryOfIssuences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryOfIssuences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountryOfIssuences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCountryOfIssuences() {
        if (countryOfIssuences == null) {
            countryOfIssuences = new ArrayList<String>();
        }
        return this.countryOfIssuences;
    }

    /**
     * Gets the value of the paymentCurrencies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentCurrencies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentCurrencies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPaymentCurrencies() {
        if (paymentCurrencies == null) {
            paymentCurrencies = new ArrayList<String>();
        }
        return this.paymentCurrencies;
    }

    public APMSearch withSiteIds(BigInteger... values) {
        if (values!= null) {
            for (BigInteger value: values) {
                getSiteIds().add(value);
            }
        }
        return this;
    }

    public APMSearch withSiteIds(Collection<BigInteger> values) {
        if (values!= null) {
            getSiteIds().addAll(values);
        }
        return this;
    }

    public APMSearch withALOCRecordId(String value) {
        setALOCRecordId(value);
        return this;
    }

    public APMSearch withALOCRecordNumber(BigInteger value) {
        setALOCRecordNumber(value);
        return this;
    }

    public APMSearch withSitePrefix(String value) {
        setSitePrefix(value);
        return this;
    }

    public APMSearch withBankReferenceNumber(String value) {
        setBankReferenceNumber(value);
        return this;
    }

    public APMSearch withApplicant(String value) {
        setApplicant(value);
        return this;
    }

    public APMSearch withBeneficiary(String value) {
        setBeneficiary(value);
        return this;
    }

    public APMSearch withBUC(String value) {
        setBUC(value);
        return this;
    }

    public APMSearch withADN(String value) {
        setADN(value);
        return this;
    }

    public APMSearch withInstrumentAmount(BigDecimal value) {
        setInstrumentAmount(value);
        return this;
    }

    public APMSearch withInstrumentAmountFrom(BigDecimal value) {
        setInstrumentAmountFrom(value);
        return this;
    }

    public APMSearch withInstrumentAmountTo(BigDecimal value) {
        setInstrumentAmountTo(value);
        return this;
    }

    public APMSearch withPaymentAmount(BigDecimal value) {
        setPaymentAmount(value);
        return this;
    }

    public APMSearch withPaymentDate(Calendar value) {
        setPaymentDate(value);
        return this;
    }

    public APMSearch withPaymentDateFrom(Calendar value) {
        setPaymentDateFrom(value);
        return this;
    }

    public APMSearch withPaymentDateTo(Calendar value) {
        setPaymentDateTo(value);
        return this;
    }

    public APMSearch withInstrumentCurrency(String value) {
        setInstrumentCurrency(value);
        return this;
    }

    public APMSearch withForeignExpiryDate(Calendar value) {
        setForeignExpiryDate(value);
        return this;
    }

    public APMSearch withPaymentCurrency(String value) {
        setPaymentCurrency(value);
        return this;
    }

    public APMSearch withPaymentBank(String value) {
        setPaymentBank(value);
        return this;
    }

    public APMSearch withCountryOfIssuences(String... values) {
        if (values!= null) {
            for (String value: values) {
                getCountryOfIssuences().add(value);
            }
        }
        return this;
    }

    public APMSearch withCountryOfIssuences(Collection<String> values) {
        if (values!= null) {
            getCountryOfIssuences().addAll(values);
        }
        return this;
    }

    public APMSearch withPaymentCurrencies(String... values) {
        if (values!= null) {
            for (String value: values) {
                getPaymentCurrencies().add(value);
            }
        }
        return this;
    }

    public APMSearch withPaymentCurrencies(Collection<String> values) {
        if (values!= null) {
            getPaymentCurrencies().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the siteIds property.
     * 
     * @param siteIds
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSiteIds(List<BigInteger> siteIds) {
        this.siteIds = siteIds;
    }

    /**
     * Sets the value of the countryOfIssuences property.
     * 
     * @param countryOfIssuences
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIssuences(List<String> countryOfIssuences) {
        this.countryOfIssuences = countryOfIssuences;
    }

    /**
     * Sets the value of the paymentCurrencies property.
     * 
     * @param paymentCurrencies
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCurrencies(List<String> paymentCurrencies) {
        this.paymentCurrencies = paymentCurrencies;
    }

}
