//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ANALYS_PERIOD_ST_DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ANALYS_PERIOD_END_DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BANK_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COUNTRY_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CURRENCY_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SITE_ID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GB_BANK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GB_COUNTRY_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GB_CURRENCY_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GB_SITE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BIDSUCCESS_USER_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalofBids" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalofReplies" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalWon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalLost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalOpt-out" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalExpired" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Won" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Lost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "analysperiodstdt",
    "analysperiodenddt",
    "bankname",
    "countryissue",
    "currencyissue",
    "siteids",
    "gbbank",
    "gbcountryissue",
    "gbcurrencyissue",
    "gbsiteid",
    "bidsuccessusersso",
    "totalofBids",
    "totalofReplies",
    "totalWon",
    "totalLost",
    "totalOptOut",
    "totalExpired",
    "won",
    "lost"
})
@XmlRootElement(name = "BidSuccessDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
public class BidSuccessDetails
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ANALYS_PERIOD_ST_DT", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String analysperiodstdt;
    @XmlElement(name = "ANALYS_PERIOD_END_DT", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String analysperiodenddt;
    @XmlElement(name = "BANK_NAME", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String bankname;
    @XmlElement(name = "COUNTRY_ISSUE", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String countryissue;
    @XmlElement(name = "CURRENCY_ISSUE", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String currencyissue;
    @XmlElement(name = "SITE_ID", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected List<String> siteids;
    @XmlElement(name = "GB_BANK", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String gbbank;
    @XmlElement(name = "GB_COUNTRY_ISSUE", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String gbcountryissue;
    @XmlElement(name = "GB_CURRENCY_ISSUE", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String gbcurrencyissue;
    @XmlElement(name = "GB_SITE_ID", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String gbsiteid;
    @XmlElement(name = "BIDSUCCESS_USER_SSO", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String bidsuccessusersso;
    @XmlElement(name = "TotalofBids", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String totalofBids;
    @XmlElement(name = "TotalofReplies", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String totalofReplies;
    @XmlElement(name = "TotalWon", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String totalWon;
    @XmlElement(name = "TotalLost", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String totalLost;
    @XmlElement(name = "TotalOpt-out", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String totalOptOut;
    @XmlElement(name = "TotalExpired", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String totalExpired;
    @XmlElement(name = "Won", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String won;
    @XmlElement(name = "Lost", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected String lost;

    /**
     * Gets the value of the analysperiodstdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANALYSPERIODSTDT() {
        return analysperiodstdt;
    }

    /**
     * Sets the value of the analysperiodstdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANALYSPERIODSTDT(String value) {
        this.analysperiodstdt = value;
    }

    /**
     * Gets the value of the analysperiodenddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANALYSPERIODENDDT() {
        return analysperiodenddt;
    }

    /**
     * Sets the value of the analysperiodenddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANALYSPERIODENDDT(String value) {
        this.analysperiodenddt = value;
    }

    /**
     * Gets the value of the bankname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKNAME() {
        return bankname;
    }

    /**
     * Sets the value of the bankname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKNAME(String value) {
        this.bankname = value;
    }

    /**
     * Gets the value of the countryissue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYISSUE() {
        return countryissue;
    }

    /**
     * Sets the value of the countryissue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYISSUE(String value) {
        this.countryissue = value;
    }

    /**
     * Gets the value of the currencyissue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRENCYISSUE() {
        return currencyissue;
    }

    /**
     * Sets the value of the currencyissue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRENCYISSUE(String value) {
        this.currencyissue = value;
    }

    /**
     * Gets the value of the siteids property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteids property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSITEIDS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSITEIDS() {
        if (siteids == null) {
            siteids = new ArrayList<String>();
        }
        return this.siteids;
    }

    /**
     * Gets the value of the gbbank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBBANK() {
        return gbbank;
    }

    /**
     * Sets the value of the gbbank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBBANK(String value) {
        this.gbbank = value;
    }

    /**
     * Gets the value of the gbcountryissue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBCOUNTRYISSUE() {
        return gbcountryissue;
    }

    /**
     * Sets the value of the gbcountryissue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBCOUNTRYISSUE(String value) {
        this.gbcountryissue = value;
    }

    /**
     * Gets the value of the gbcurrencyissue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBCURRENCYISSUE() {
        return gbcurrencyissue;
    }

    /**
     * Sets the value of the gbcurrencyissue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBCURRENCYISSUE(String value) {
        this.gbcurrencyissue = value;
    }

    /**
     * Gets the value of the gbsiteid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBSITEID() {
        return gbsiteid;
    }

    /**
     * Sets the value of the gbsiteid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBSITEID(String value) {
        this.gbsiteid = value;
    }

    /**
     * Gets the value of the bidsuccessusersso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDSUCCESSUSERSSO() {
        return bidsuccessusersso;
    }

    /**
     * Sets the value of the bidsuccessusersso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDSUCCESSUSERSSO(String value) {
        this.bidsuccessusersso = value;
    }

    /**
     * Gets the value of the totalofBids property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalofBids() {
        return totalofBids;
    }

    /**
     * Sets the value of the totalofBids property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalofBids(String value) {
        this.totalofBids = value;
    }

    /**
     * Gets the value of the totalofReplies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalofReplies() {
        return totalofReplies;
    }

    /**
     * Sets the value of the totalofReplies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalofReplies(String value) {
        this.totalofReplies = value;
    }

    /**
     * Gets the value of the totalWon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalWon() {
        return totalWon;
    }

    /**
     * Sets the value of the totalWon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalWon(String value) {
        this.totalWon = value;
    }

    /**
     * Gets the value of the totalLost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalLost() {
        return totalLost;
    }

    /**
     * Sets the value of the totalLost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalLost(String value) {
        this.totalLost = value;
    }

    /**
     * Gets the value of the totalOptOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalOptOut() {
        return totalOptOut;
    }

    /**
     * Sets the value of the totalOptOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalOptOut(String value) {
        this.totalOptOut = value;
    }

    /**
     * Gets the value of the totalExpired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalExpired() {
        return totalExpired;
    }

    /**
     * Sets the value of the totalExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalExpired(String value) {
        this.totalExpired = value;
    }

    /**
     * Gets the value of the won property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWon() {
        return won;
    }

    /**
     * Sets the value of the won property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWon(String value) {
        this.won = value;
    }

    /**
     * Gets the value of the lost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLost() {
        return lost;
    }

    /**
     * Sets the value of the lost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLost(String value) {
        this.lost = value;
    }

    public BidSuccessDetails withANALYSPERIODSTDT(String value) {
        setANALYSPERIODSTDT(value);
        return this;
    }

    public BidSuccessDetails withANALYSPERIODENDDT(String value) {
        setANALYSPERIODENDDT(value);
        return this;
    }

    public BidSuccessDetails withBANKNAME(String value) {
        setBANKNAME(value);
        return this;
    }

    public BidSuccessDetails withCOUNTRYISSUE(String value) {
        setCOUNTRYISSUE(value);
        return this;
    }

    public BidSuccessDetails withCURRENCYISSUE(String value) {
        setCURRENCYISSUE(value);
        return this;
    }

    public BidSuccessDetails withSITEIDS(String... values) {
        if (values!= null) {
            for (String value: values) {
                getSITEIDS().add(value);
            }
        }
        return this;
    }

    public BidSuccessDetails withSITEIDS(Collection<String> values) {
        if (values!= null) {
            getSITEIDS().addAll(values);
        }
        return this;
    }

    public BidSuccessDetails withGBBANK(String value) {
        setGBBANK(value);
        return this;
    }

    public BidSuccessDetails withGBCOUNTRYISSUE(String value) {
        setGBCOUNTRYISSUE(value);
        return this;
    }

    public BidSuccessDetails withGBCURRENCYISSUE(String value) {
        setGBCURRENCYISSUE(value);
        return this;
    }

    public BidSuccessDetails withGBSITEID(String value) {
        setGBSITEID(value);
        return this;
    }

    public BidSuccessDetails withBIDSUCCESSUSERSSO(String value) {
        setBIDSUCCESSUSERSSO(value);
        return this;
    }

    public BidSuccessDetails withTotalofBids(String value) {
        setTotalofBids(value);
        return this;
    }

    public BidSuccessDetails withTotalofReplies(String value) {
        setTotalofReplies(value);
        return this;
    }

    public BidSuccessDetails withTotalWon(String value) {
        setTotalWon(value);
        return this;
    }

    public BidSuccessDetails withTotalLost(String value) {
        setTotalLost(value);
        return this;
    }

    public BidSuccessDetails withTotalOptOut(String value) {
        setTotalOptOut(value);
        return this;
    }

    public BidSuccessDetails withTotalExpired(String value) {
        setTotalExpired(value);
        return this;
    }

    public BidSuccessDetails withWon(String value) {
        setWon(value);
        return this;
    }

    public BidSuccessDetails withLost(String value) {
        setLost(value);
        return this;
    }

    /**
     * Sets the value of the siteids property.
     * 
     * @param siteids
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEIDS(List<String> siteids) {
        this.siteids = siteids;
    }

}
