//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 03:04:05 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Delegation_Config_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd}Instrument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Instr_Amt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Instr_Base_Amt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Instr_End_Amt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Notification_Caluse_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Cure_PeriodIndicator_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GE_App_Draw_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GE_ProposedDoc_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Customer_Proposal_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd}Group_Assignment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OpCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Row_Num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "delegationConfigId",
    "instruments",
    "instrAmt",
    "instrBaseAmt",
    "instrEndAmt",
    "notificationCaluseFlag",
    "curePeriodIndicatorFlag",
    "geAppDrawFlag",
    "geProposedDocFlag",
    "customerProposalFlag",
    "groupAssignments",
    "opCode",
    "rowNum"
})
@XmlRootElement(name = "Delegation_Config", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
public class DelegationConfig
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Delegation_Config_Id", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected BigInteger delegationConfigId;
    @XmlElement(name = "Instrument", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected List<Instrument> instruments;
    @XmlElement(name = "Instr_Amt", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected BigDecimal instrAmt;
    @XmlElement(name = "Instr_Base_Amt", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected BigDecimal instrBaseAmt;
    @XmlElement(name = "Instr_End_Amt", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected BigDecimal instrEndAmt;
    @XmlElement(name = "Notification_Caluse_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected String notificationCaluseFlag;
    @XmlElement(name = "Cure_PeriodIndicator_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected String curePeriodIndicatorFlag;
    @XmlElement(name = "GE_App_Draw_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected String geAppDrawFlag;
    @XmlElement(name = "GE_ProposedDoc_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected Boolean geProposedDocFlag;
    @XmlElement(name = "Customer_Proposal_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected Boolean customerProposalFlag;
    @XmlElement(name = "Group_Assignment", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected List<GroupAssignment> groupAssignments;
    @XmlElement(name = "OpCode", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected String opCode;
    @XmlElement(name = "Row_Num", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/DelegationConfiguration.xsd")
    protected String rowNum;

    /**
     * Gets the value of the delegationConfigId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDelegationConfigId() {
        return delegationConfigId;
    }

    /**
     * Sets the value of the delegationConfigId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDelegationConfigId(BigInteger value) {
        this.delegationConfigId = value;
    }

    /**
     * Gets the value of the instruments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instruments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstruments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Instrument }
     * 
     * 
     */
    public List<Instrument> getInstruments() {
        if (instruments == null) {
            instruments = new ArrayList<Instrument>();
        }
        return this.instruments;
    }

    /**
     * Gets the value of the instrAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrAmt() {
        return instrAmt;
    }

    /**
     * Sets the value of the instrAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrAmt(BigDecimal value) {
        this.instrAmt = value;
    }

    /**
     * Gets the value of the instrBaseAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrBaseAmt() {
        return instrBaseAmt;
    }

    /**
     * Sets the value of the instrBaseAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrBaseAmt(BigDecimal value) {
        this.instrBaseAmt = value;
    }

    /**
     * Gets the value of the instrEndAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrEndAmt() {
        return instrEndAmt;
    }

    /**
     * Sets the value of the instrEndAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrEndAmt(BigDecimal value) {
        this.instrEndAmt = value;
    }

    /**
     * Gets the value of the notificationCaluseFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationCaluseFlag() {
        return notificationCaluseFlag;
    }

    /**
     * Sets the value of the notificationCaluseFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationCaluseFlag(String value) {
        this.notificationCaluseFlag = value;
    }

    /**
     * Gets the value of the curePeriodIndicatorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurePeriodIndicatorFlag() {
        return curePeriodIndicatorFlag;
    }

    /**
     * Sets the value of the curePeriodIndicatorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurePeriodIndicatorFlag(String value) {
        this.curePeriodIndicatorFlag = value;
    }

    /**
     * Gets the value of the geAppDrawFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGEAppDrawFlag() {
        return geAppDrawFlag;
    }

    /**
     * Sets the value of the geAppDrawFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGEAppDrawFlag(String value) {
        this.geAppDrawFlag = value;
    }

    /**
     * Gets the value of the geProposedDocFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGEProposedDocFlag() {
        return geProposedDocFlag;
    }

    /**
     * Sets the value of the geProposedDocFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGEProposedDocFlag(Boolean value) {
        this.geProposedDocFlag = value;
    }

    /**
     * Gets the value of the customerProposalFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomerProposalFlag() {
        return customerProposalFlag;
    }

    /**
     * Sets the value of the customerProposalFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomerProposalFlag(Boolean value) {
        this.customerProposalFlag = value;
    }

    /**
     * Gets the value of the groupAssignments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupAssignments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupAssignments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupAssignment }
     * 
     * 
     */
    public List<GroupAssignment> getGroupAssignments() {
        if (groupAssignments == null) {
            groupAssignments = new ArrayList<GroupAssignment>();
        }
        return this.groupAssignments;
    }

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the rowNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowNum() {
        return rowNum;
    }

    /**
     * Sets the value of the rowNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowNum(String value) {
        this.rowNum = value;
    }

    public DelegationConfig withDelegationConfigId(BigInteger value) {
        setDelegationConfigId(value);
        return this;
    }

    public DelegationConfig withInstruments(Instrument... values) {
        if (values!= null) {
            for (Instrument value: values) {
                getInstruments().add(value);
            }
        }
        return this;
    }

    public DelegationConfig withInstruments(Collection<Instrument> values) {
        if (values!= null) {
            getInstruments().addAll(values);
        }
        return this;
    }

    public DelegationConfig withInstrAmt(BigDecimal value) {
        setInstrAmt(value);
        return this;
    }

    public DelegationConfig withInstrBaseAmt(BigDecimal value) {
        setInstrBaseAmt(value);
        return this;
    }

    public DelegationConfig withInstrEndAmt(BigDecimal value) {
        setInstrEndAmt(value);
        return this;
    }

    public DelegationConfig withNotificationCaluseFlag(String value) {
        setNotificationCaluseFlag(value);
        return this;
    }

    public DelegationConfig withCurePeriodIndicatorFlag(String value) {
        setCurePeriodIndicatorFlag(value);
        return this;
    }

    public DelegationConfig withGEAppDrawFlag(String value) {
        setGEAppDrawFlag(value);
        return this;
    }

    public DelegationConfig withGEProposedDocFlag(Boolean value) {
        setGEProposedDocFlag(value);
        return this;
    }

    public DelegationConfig withCustomerProposalFlag(Boolean value) {
        setCustomerProposalFlag(value);
        return this;
    }

    public DelegationConfig withGroupAssignments(GroupAssignment... values) {
        if (values!= null) {
            for (GroupAssignment value: values) {
                getGroupAssignments().add(value);
            }
        }
        return this;
    }

    public DelegationConfig withGroupAssignments(Collection<GroupAssignment> values) {
        if (values!= null) {
            getGroupAssignments().addAll(values);
        }
        return this;
    }

    public DelegationConfig withOpCode(String value) {
        setOpCode(value);
        return this;
    }

    public DelegationConfig withRowNum(String value) {
        setRowNum(value);
        return this;
    }

    /**
     * Sets the value of the instruments property.
     * 
     * @param instruments
     *     allowed object is
     *     {@link Instrument }
     *     
     */
    public void setInstruments(List<Instrument> instruments) {
        this.instruments = instruments;
    }

    /**
     * Sets the value of the groupAssignments property.
     * 
     * @param groupAssignments
     *     allowed object is
     *     {@link GroupAssignment }
     *     
     */
    public void setGroupAssignments(List<GroupAssignment> groupAssignments) {
        this.groupAssignments = groupAssignments;
    }

}
