//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Op_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delivery_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ecopy_Myself" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ecopy_Other_GEPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd}Recipient" minOccurs="0"/>
 *         &lt;element name="Company_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State_Province_Cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State_Province" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ZIP_Postalcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Country_Cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Phone_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Special_Instructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delivery_Designation_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/ALOCCommon.xsd}ActionDetails" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Requires_Edits" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Send_Back_Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Use_Previous_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Change_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opCode",
    "deliveryType",
    "ecopyMyself",
    "ecopyOtherGEPerson",
    "recipient",
    "companyName",
    "addressId",
    "firstName",
    "lastName",
    "title",
    "address1",
    "address2",
    "city",
    "stateProvinceCd",
    "stateProvince",
    "zipPostalcode",
    "countryCd",
    "country",
    "phoneNo",
    "specialInstructions",
    "deliveryDesignationFlag",
    "actionDetails",
    "comments",
    "requiresEdits",
    "sendBackNotes",
    "usePreviousAddress",
    "changeFlag"
})
@XmlRootElement(name = "DeliveryInstructions", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
public class DeliveryInstructions
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Op_Code", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String opCode;
    @XmlElement(name = "Delivery_Type", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String deliveryType;
    @XmlElement(name = "Ecopy_Myself", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String ecopyMyself;
    @XmlElement(name = "Ecopy_Other_GEPerson", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String ecopyOtherGEPerson;
    @XmlElement(name = "Recipient", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected Recipient recipient;
    @XmlElement(name = "Company_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String companyName;
    @XmlElement(name = "Address_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected BigInteger addressId;
    @XmlElement(name = "First_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String firstName;
    @XmlElement(name = "Last_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String lastName;
    @XmlElement(name = "Title", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String title;
    @XmlElement(name = "Address1", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String address1;
    @XmlElement(name = "Address2", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String address2;
    @XmlElement(name = "City", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String city;
    @XmlElement(name = "State_Province_Cd", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String stateProvinceCd;
    @XmlElement(name = "State_Province", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String stateProvince;
    @XmlElement(name = "ZIP_Postalcode", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String zipPostalcode;
    @XmlElement(name = "Country_Cd", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String countryCd;
    @XmlElement(name = "Country", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String country;
    @XmlElement(name = "Phone_No", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String phoneNo;
    @XmlElement(name = "Special_Instructions", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String specialInstructions;
    @XmlElement(name = "Delivery_Designation_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String deliveryDesignationFlag;
    @XmlElement(name = "ActionDetails", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ALOCCommon.xsd")
    protected ActionDetails actionDetails;
    @XmlElement(name = "Comments", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String comments;
    @XmlElement(name = "Requires_Edits", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected Boolean requiresEdits;
    @XmlElement(name = "Send_Back_Notes", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String sendBackNotes;
    @XmlElement(name = "Use_Previous_Address", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String usePreviousAddress;
    @XmlElement(name = "Change_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected String changeFlag;

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryType(String value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the ecopyMyself property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcopyMyself() {
        return ecopyMyself;
    }

    /**
     * Sets the value of the ecopyMyself property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcopyMyself(String value) {
        this.ecopyMyself = value;
    }

    /**
     * Gets the value of the ecopyOtherGEPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcopyOtherGEPerson() {
        return ecopyOtherGEPerson;
    }

    /**
     * Sets the value of the ecopyOtherGEPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcopyOtherGEPerson(String value) {
        this.ecopyOtherGEPerson = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link Recipient }
     *     
     */
    public Recipient getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipient }
     *     
     */
    public void setRecipient(Recipient value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the addressId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddressId() {
        return addressId;
    }

    /**
     * Sets the value of the addressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddressId(BigInteger value) {
        this.addressId = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the stateProvinceCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateProvinceCd() {
        return stateProvinceCd;
    }

    /**
     * Sets the value of the stateProvinceCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateProvinceCd(String value) {
        this.stateProvinceCd = value;
    }

    /**
     * Gets the value of the stateProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * Sets the value of the stateProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateProvince(String value) {
        this.stateProvince = value;
    }

    /**
     * Gets the value of the zipPostalcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPPostalcode() {
        return zipPostalcode;
    }

    /**
     * Sets the value of the zipPostalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPPostalcode(String value) {
        this.zipPostalcode = value;
    }

    /**
     * Gets the value of the countryCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCd() {
        return countryCd;
    }

    /**
     * Sets the value of the countryCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCd(String value) {
        this.countryCd = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the phoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * Sets the value of the phoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNo(String value) {
        this.phoneNo = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstructions(String value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the deliveryDesignationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDesignationFlag() {
        return deliveryDesignationFlag;
    }

    /**
     * Sets the value of the deliveryDesignationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDesignationFlag(String value) {
        this.deliveryDesignationFlag = value;
    }

    /**
     * Gets the value of the actionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ActionDetails }
     *     
     */
    public ActionDetails getActionDetails() {
        return actionDetails;
    }

    /**
     * Sets the value of the actionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionDetails }
     *     
     */
    public void setActionDetails(ActionDetails value) {
        this.actionDetails = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the requiresEdits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresEdits() {
        return requiresEdits;
    }

    /**
     * Sets the value of the requiresEdits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresEdits(Boolean value) {
        this.requiresEdits = value;
    }

    /**
     * Gets the value of the sendBackNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendBackNotes() {
        return sendBackNotes;
    }

    /**
     * Sets the value of the sendBackNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendBackNotes(String value) {
        this.sendBackNotes = value;
    }

    /**
     * Gets the value of the usePreviousAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsePreviousAddress() {
        return usePreviousAddress;
    }

    /**
     * Sets the value of the usePreviousAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsePreviousAddress(String value) {
        this.usePreviousAddress = value;
    }

    /**
     * Gets the value of the changeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeFlag() {
        return changeFlag;
    }

    /**
     * Sets the value of the changeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeFlag(String value) {
        this.changeFlag = value;
    }

    public DeliveryInstructions withOpCode(String value) {
        setOpCode(value);
        return this;
    }

    public DeliveryInstructions withDeliveryType(String value) {
        setDeliveryType(value);
        return this;
    }

    public DeliveryInstructions withEcopyMyself(String value) {
        setEcopyMyself(value);
        return this;
    }

    public DeliveryInstructions withEcopyOtherGEPerson(String value) {
        setEcopyOtherGEPerson(value);
        return this;
    }

    public DeliveryInstructions withRecipient(Recipient value) {
        setRecipient(value);
        return this;
    }

    public DeliveryInstructions withCompanyName(String value) {
        setCompanyName(value);
        return this;
    }

    public DeliveryInstructions withAddressId(BigInteger value) {
        setAddressId(value);
        return this;
    }

    public DeliveryInstructions withFirstName(String value) {
        setFirstName(value);
        return this;
    }

    public DeliveryInstructions withLastName(String value) {
        setLastName(value);
        return this;
    }

    public DeliveryInstructions withTitle(String value) {
        setTitle(value);
        return this;
    }

    public DeliveryInstructions withAddress1(String value) {
        setAddress1(value);
        return this;
    }

    public DeliveryInstructions withAddress2(String value) {
        setAddress2(value);
        return this;
    }

    public DeliveryInstructions withCity(String value) {
        setCity(value);
        return this;
    }

    public DeliveryInstructions withStateProvinceCd(String value) {
        setStateProvinceCd(value);
        return this;
    }

    public DeliveryInstructions withStateProvince(String value) {
        setStateProvince(value);
        return this;
    }

    public DeliveryInstructions withZIPPostalcode(String value) {
        setZIPPostalcode(value);
        return this;
    }

    public DeliveryInstructions withCountryCd(String value) {
        setCountryCd(value);
        return this;
    }

    public DeliveryInstructions withCountry(String value) {
        setCountry(value);
        return this;
    }

    public DeliveryInstructions withPhoneNo(String value) {
        setPhoneNo(value);
        return this;
    }

    public DeliveryInstructions withSpecialInstructions(String value) {
        setSpecialInstructions(value);
        return this;
    }

    public DeliveryInstructions withDeliveryDesignationFlag(String value) {
        setDeliveryDesignationFlag(value);
        return this;
    }

    public DeliveryInstructions withActionDetails(ActionDetails value) {
        setActionDetails(value);
        return this;
    }

    public DeliveryInstructions withComments(String value) {
        setComments(value);
        return this;
    }

    public DeliveryInstructions withRequiresEdits(Boolean value) {
        setRequiresEdits(value);
        return this;
    }

    public DeliveryInstructions withSendBackNotes(String value) {
        setSendBackNotes(value);
        return this;
    }

    public DeliveryInstructions withUsePreviousAddress(String value) {
        setUsePreviousAddress(value);
        return this;
    }

    public DeliveryInstructions withChangeFlag(String value) {
        setChangeFlag(value);
        return this;
    }

}
