//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/FeeHistory.xsd}FeeHistory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Request_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/MsgHeader.xsd}Msg_Header" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "feeHistories",
    "requestId",
    "msgHeader"
})
@XmlRootElement(name = "GetFeeHistoryDetails", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/GetFeeHistoryDetails.xsd")
public class GetFeeHistoryDetails
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "FeeHistory", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/FeeHistory.xsd")
    protected List<FeeHistory> feeHistories;
    @XmlElement(name = "Request_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/GetFeeHistoryDetails.xsd")
    protected BigInteger requestId;
    @XmlElement(name = "Msg_Header", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/MsgHeader.xsd")
    protected MsgHeader msgHeader;

    /**
     * Gets the value of the feeHistories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feeHistories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeeHistories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeeHistory }
     * 
     * 
     */
    public List<FeeHistory> getFeeHistories() {
        if (feeHistories == null) {
            feeHistories = new ArrayList<FeeHistory>();
        }
        return this.feeHistories;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestId(BigInteger value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    public GetFeeHistoryDetails withFeeHistories(FeeHistory... values) {
        if (values!= null) {
            for (FeeHistory value: values) {
                getFeeHistories().add(value);
            }
        }
        return this;
    }

    public GetFeeHistoryDetails withFeeHistories(Collection<FeeHistory> values) {
        if (values!= null) {
            getFeeHistories().addAll(values);
        }
        return this;
    }

    public GetFeeHistoryDetails withRequestId(BigInteger value) {
        setRequestId(value);
        return this;
    }

    public GetFeeHistoryDetails withMsgHeader(MsgHeader value) {
        setMsgHeader(value);
        return this;
    }

    /**
     * Sets the value of the feeHistories property.
     * 
     * @param feeHistories
     *     allowed object is
     *     {@link FeeHistory }
     *     
     */
    public void setFeeHistories(List<FeeHistory> feeHistories) {
        this.feeHistories = feeHistories;
    }

}
