//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADN_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BUC_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IBS_Message_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="IBS_Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Validation_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Contact_Person_Details" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="User_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adnCode",
    "bucCode",
    "ibsMessageId",
    "ibsMessage",
    "validationFlag",
    "contactPersonDetails"
})
@XmlRootElement(name = "IBS", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
public class IBS
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ADN_Code", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
    protected String adnCode;
    @XmlElement(name = "BUC_Code", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
    protected String bucCode;
    @XmlElement(name = "IBS_Message_Id", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
    protected BigInteger ibsMessageId;
    @XmlElement(name = "IBS_Message", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
    protected String ibsMessage;
    @XmlElement(name = "Validation_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
    protected Boolean validationFlag;
    @XmlElement(name = "Contact_Person_Details", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
    protected IBS.ContactPersonDetails contactPersonDetails;

    /**
     * Gets the value of the adnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADNCode() {
        return adnCode;
    }

    /**
     * Sets the value of the adnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADNCode(String value) {
        this.adnCode = value;
    }

    /**
     * Gets the value of the bucCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUCCode() {
        return bucCode;
    }

    /**
     * Sets the value of the bucCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUCCode(String value) {
        this.bucCode = value;
    }

    /**
     * Gets the value of the ibsMessageId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIBSMessageId() {
        return ibsMessageId;
    }

    /**
     * Sets the value of the ibsMessageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIBSMessageId(BigInteger value) {
        this.ibsMessageId = value;
    }

    /**
     * Gets the value of the ibsMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBSMessage() {
        return ibsMessage;
    }

    /**
     * Sets the value of the ibsMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBSMessage(String value) {
        this.ibsMessage = value;
    }

    /**
     * Gets the value of the validationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidationFlag() {
        return validationFlag;
    }

    /**
     * Sets the value of the validationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidationFlag(Boolean value) {
        this.validationFlag = value;
    }

    /**
     * Gets the value of the contactPersonDetails property.
     * 
     * @return
     *     possible object is
     *     {@link IBS.ContactPersonDetails }
     *     
     */
    public IBS.ContactPersonDetails getContactPersonDetails() {
        return contactPersonDetails;
    }

    /**
     * Sets the value of the contactPersonDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link IBS.ContactPersonDetails }
     *     
     */
    public void setContactPersonDetails(IBS.ContactPersonDetails value) {
        this.contactPersonDetails = value;
    }

    public IBS withADNCode(String value) {
        setADNCode(value);
        return this;
    }

    public IBS withBUCCode(String value) {
        setBUCCode(value);
        return this;
    }

    public IBS withIBSMessageId(BigInteger value) {
        setIBSMessageId(value);
        return this;
    }

    public IBS withIBSMessage(String value) {
        setIBSMessage(value);
        return this;
    }

    public IBS withValidationFlag(Boolean value) {
        setValidationFlag(value);
        return this;
    }

    public IBS withContactPersonDetails(IBS.ContactPersonDetails value) {
        setContactPersonDetails(value);
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="User_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userSSO",
        "firstName",
        "lastName",
        "phone"
    })
    public static class ContactPersonDetails
        extends JAXBObjectSecureSerializer
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "User_SSO", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
        protected String userSSO;
        @XmlElement(name = "First_Name", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
        protected String firstName;
        @XmlElement(name = "Last_Name", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
        protected String lastName;
        @XmlElement(name = "Phone", namespace = "http://treasury.ge.com/schemas/ALOC/SiteAdmin/IBS.xsd")
        protected String phone;

        /**
         * Gets the value of the userSSO property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserSSO() {
            return userSSO;
        }

        /**
         * Sets the value of the userSSO property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserSSO(String value) {
            this.userSSO = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhone() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhone(String value) {
            this.phone = value;
        }

        public IBS.ContactPersonDetails withUserSSO(String value) {
            setUserSSO(value);
            return this;
        }

        public IBS.ContactPersonDetails withFirstName(String value) {
            setFirstName(value);
            return this;
        }

        public IBS.ContactPersonDetails withLastName(String value) {
            setLastName(value);
            return this;
        }

        public IBS.ContactPersonDetails withPhone(String value) {
            setPhone(value);
            return this;
        }

    }

}
