//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADN" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ADN_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="ADN_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ADN_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BUC" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BUC_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="BUC_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BUC_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IBS_Message_Details" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ADN_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BUC_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IBS_Message_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="IBS_Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Contact_Person_Details" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="User_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adns",
    "bucs",
    "ibsMessageDetails"
})
@XmlRootElement(name = "IBSDetails", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
public class IBSDetails
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ADN", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
    protected List<IBSDetails.ADN> adns;
    @XmlElement(name = "BUC", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
    protected List<IBSDetails.BUC> bucs;
    @XmlElement(name = "IBS_Message_Details", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
    protected List<IBSDetails.IBSMessageDetails> ibsMessageDetails;

    /**
     * Gets the value of the adns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADNS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IBSDetails.ADN }
     * 
     * 
     */
    public List<IBSDetails.ADN> getADNS() {
        if (adns == null) {
            adns = new ArrayList<IBSDetails.ADN>();
        }
        return this.adns;
    }

    /**
     * Gets the value of the bucs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bucs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBUCS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IBSDetails.BUC }
     * 
     * 
     */
    public List<IBSDetails.BUC> getBUCS() {
        if (bucs == null) {
            bucs = new ArrayList<IBSDetails.BUC>();
        }
        return this.bucs;
    }

    /**
     * Gets the value of the ibsMessageDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ibsMessageDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIBSMessageDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IBSDetails.IBSMessageDetails }
     * 
     * 
     */
    public List<IBSDetails.IBSMessageDetails> getIBSMessageDetails() {
        if (ibsMessageDetails == null) {
            ibsMessageDetails = new ArrayList<IBSDetails.IBSMessageDetails>();
        }
        return this.ibsMessageDetails;
    }

    public IBSDetails withADNS(IBSDetails.ADN... values) {
        if (values!= null) {
            for (IBSDetails.ADN value: values) {
                getADNS().add(value);
            }
        }
        return this;
    }

    public IBSDetails withADNS(Collection<IBSDetails.ADN> values) {
        if (values!= null) {
            getADNS().addAll(values);
        }
        return this;
    }

    public IBSDetails withBUCS(IBSDetails.BUC... values) {
        if (values!= null) {
            for (IBSDetails.BUC value: values) {
                getBUCS().add(value);
            }
        }
        return this;
    }

    public IBSDetails withBUCS(Collection<IBSDetails.BUC> values) {
        if (values!= null) {
            getBUCS().addAll(values);
        }
        return this;
    }

    public IBSDetails withIBSMessageDetails(IBSDetails.IBSMessageDetails... values) {
        if (values!= null) {
            for (IBSDetails.IBSMessageDetails value: values) {
                getIBSMessageDetails().add(value);
            }
        }
        return this;
    }

    public IBSDetails withIBSMessageDetails(Collection<IBSDetails.IBSMessageDetails> values) {
        if (values!= null) {
            getIBSMessageDetails().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the adns property.
     * 
     * @param adns
     *     allowed object is
     *     {@link IBSDetails.ADN }
     *     
     */
    public void setADNS(List<IBSDetails.ADN> adns) {
        this.adns = adns;
    }

    /**
     * Sets the value of the bucs property.
     * 
     * @param bucs
     *     allowed object is
     *     {@link IBSDetails.BUC }
     *     
     */
    public void setBUCS(List<IBSDetails.BUC> bucs) {
        this.bucs = bucs;
    }

    /**
     * Sets the value of the ibsMessageDetails property.
     * 
     * @param ibsMessageDetails
     *     allowed object is
     *     {@link IBSDetails.IBSMessageDetails }
     *     
     */
    public void setIBSMessageDetails(List<IBSDetails.IBSMessageDetails> ibsMessageDetails) {
        this.ibsMessageDetails = ibsMessageDetails;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ADN_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="ADN_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ADN_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adnId",
        "adnCode",
        "adnName"
    })
    public static class ADN
        extends JAXBObjectSecureSerializer
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "ADN_Id", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected BigInteger adnId;
        @XmlElement(name = "ADN_Code", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String adnCode;
        @XmlElement(name = "ADN_Name", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String adnName;

        /**
         * Gets the value of the adnId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getADNId() {
            return adnId;
        }

        /**
         * Sets the value of the adnId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setADNId(BigInteger value) {
            this.adnId = value;
        }

        /**
         * Gets the value of the adnCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADNCode() {
            return adnCode;
        }

        /**
         * Sets the value of the adnCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADNCode(String value) {
            this.adnCode = value;
        }

        /**
         * Gets the value of the adnName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADNName() {
            return adnName;
        }

        /**
         * Sets the value of the adnName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADNName(String value) {
            this.adnName = value;
        }

        public IBSDetails.ADN withADNId(BigInteger value) {
            setADNId(value);
            return this;
        }

        public IBSDetails.ADN withADNCode(String value) {
            setADNCode(value);
            return this;
        }

        public IBSDetails.ADN withADNName(String value) {
            setADNName(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BUC_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="BUC_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BUC_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bucId",
        "bucCode",
        "bucName"
    })
    public static class BUC
        extends JAXBObjectSecureSerializer
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "BUC_Id", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected BigInteger bucId;
        @XmlElement(name = "BUC_Code", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String bucCode;
        @XmlElement(name = "BUC_Name", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String bucName;

        /**
         * Gets the value of the bucId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBUCId() {
            return bucId;
        }

        /**
         * Sets the value of the bucId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBUCId(BigInteger value) {
            this.bucId = value;
        }

        /**
         * Gets the value of the bucCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBUCCode() {
            return bucCode;
        }

        /**
         * Sets the value of the bucCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBUCCode(String value) {
            this.bucCode = value;
        }

        /**
         * Gets the value of the bucName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBUCName() {
            return bucName;
        }

        /**
         * Sets the value of the bucName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBUCName(String value) {
            this.bucName = value;
        }

        public IBSDetails.BUC withBUCId(BigInteger value) {
            setBUCId(value);
            return this;
        }

        public IBSDetails.BUC withBUCCode(String value) {
            setBUCCode(value);
            return this;
        }

        public IBSDetails.BUC withBUCName(String value) {
            setBUCName(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ADN_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BUC_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IBS_Message_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="IBS_Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Contact_Person_Details" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="User_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adnCode",
        "bucCode",
        "ibsMessageId",
        "ibsMessage",
        "contactPersonDetails"
    })
    public static class IBSMessageDetails
        extends JAXBObjectSecureSerializer
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "ADN_Code", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String adnCode;
        @XmlElement(name = "BUC_Code", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String bucCode;
        @XmlElement(name = "IBS_Message_Id", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected BigInteger ibsMessageId;
        @XmlElement(name = "IBS_Message", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected String ibsMessage;
        @XmlElement(name = "Contact_Person_Details", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
        protected IBSDetails.IBSMessageDetails.ContactPersonDetails contactPersonDetails;

        /**
         * Gets the value of the adnCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADNCode() {
            return adnCode;
        }

        /**
         * Sets the value of the adnCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADNCode(String value) {
            this.adnCode = value;
        }

        /**
         * Gets the value of the bucCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBUCCode() {
            return bucCode;
        }

        /**
         * Sets the value of the bucCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBUCCode(String value) {
            this.bucCode = value;
        }

        /**
         * Gets the value of the ibsMessageId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIBSMessageId() {
            return ibsMessageId;
        }

        /**
         * Sets the value of the ibsMessageId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIBSMessageId(BigInteger value) {
            this.ibsMessageId = value;
        }

        /**
         * Gets the value of the ibsMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIBSMessage() {
            return ibsMessage;
        }

        /**
         * Sets the value of the ibsMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIBSMessage(String value) {
            this.ibsMessage = value;
        }

        /**
         * Gets the value of the contactPersonDetails property.
         * 
         * @return
         *     possible object is
         *     {@link IBSDetails.IBSMessageDetails.ContactPersonDetails }
         *     
         */
        public IBSDetails.IBSMessageDetails.ContactPersonDetails getContactPersonDetails() {
            return contactPersonDetails;
        }

        /**
         * Sets the value of the contactPersonDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link IBSDetails.IBSMessageDetails.ContactPersonDetails }
         *     
         */
        public void setContactPersonDetails(IBSDetails.IBSMessageDetails.ContactPersonDetails value) {
            this.contactPersonDetails = value;
        }

        public IBSDetails.IBSMessageDetails withADNCode(String value) {
            setADNCode(value);
            return this;
        }

        public IBSDetails.IBSMessageDetails withBUCCode(String value) {
            setBUCCode(value);
            return this;
        }

        public IBSDetails.IBSMessageDetails withIBSMessageId(BigInteger value) {
            setIBSMessageId(value);
            return this;
        }

        public IBSDetails.IBSMessageDetails withIBSMessage(String value) {
            setIBSMessage(value);
            return this;
        }

        public IBSDetails.IBSMessageDetails withContactPersonDetails(IBSDetails.IBSMessageDetails.ContactPersonDetails value) {
            setContactPersonDetails(value);
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="User_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userSSO",
            "firstName",
            "lastName",
            "phone"
        })
        public static class ContactPersonDetails
            extends JAXBObjectSecureSerializer
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "User_SSO", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
            protected String userSSO;
            @XmlElement(name = "First_Name", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
            protected String firstName;
            @XmlElement(name = "Last_Name", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
            protected String lastName;
            @XmlElement(name = "Phone", namespace = "http://treasury.ge.com/schemas/ALOC/IBSDetails.xsd")
            protected String phone;

            /**
             * Gets the value of the userSSO property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserSSO() {
                return userSSO;
            }

            /**
             * Sets the value of the userSSO property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserSSO(String value) {
                this.userSSO = value;
            }

            /**
             * Gets the value of the firstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

            /**
             * Gets the value of the lastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastName() {
                return lastName;
            }

            /**
             * Sets the value of the lastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastName(String value) {
                this.lastName = value;
            }

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhone() {
                return phone;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhone(String value) {
                this.phone = value;
            }

            public IBSDetails.IBSMessageDetails.ContactPersonDetails withUserSSO(String value) {
                setUserSSO(value);
                return this;
            }

            public IBSDetails.IBSMessageDetails.ContactPersonDetails withFirstName(String value) {
                setFirstName(value);
                return this;
            }

            public IBSDetails.IBSMessageDetails.ContactPersonDetails withLastName(String value) {
                setLastName(value);
                return this;
            }

            public IBSDetails.IBSMessageDetails.ContactPersonDetails withPhone(String value) {
                setPhone(value);
                return this;
            }

        }

    }

}
