//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Op_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Le_Gold_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Le_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Principle_Info_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ge_Division_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ge_Division_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="AddressDtls" type="{http://treasury.ge.com/schemas/ALOC/RequestDetails/AddressDetails.xsd}AddressDtlsType" minOccurs="0"/>
 *         &lt;element name="Province_Of_Incorporation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Business_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/ALOCCommon.xsd}Ref_Details" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Principal_Bu_Unite_cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Principal_Acc_Dist_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IBS_Syst_Msg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IBS_Msg_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="IBS_User_Sso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IBS_First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IBS_Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IBS_Phone_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Requires_Edits" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Send_Back_Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Change_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opCode",
    "leGoldId",
    "leName",
    "principleInfoFlag",
    "geDivisionName",
    "geDivisionId",
    "addressDtls",
    "provinceOfIncorporation",
    "businessId",
    "refDetails",
    "principalBuUniteCd",
    "principalAccDistNo",
    "ibsSystMsg",
    "ibsMsgId",
    "ibsUserSso",
    "ibsFirstName",
    "ibsLastName",
    "ibsPhoneNo",
    "comments",
    "requiresEdits",
    "sendBackNotes",
    "changeFlag"
})
@XmlRootElement(name = "Principal", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
public class Principal
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Op_Code", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String opCode;
    @XmlElement(name = "Le_Gold_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String leGoldId;
    @XmlElement(name = "Le_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String leName;
    @XmlElement(name = "Principle_Info_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String principleInfoFlag;
    @XmlElement(name = "Ge_Division_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String geDivisionName;
    @XmlElement(name = "Ge_Division_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected BigInteger geDivisionId;
    @XmlElement(name = "AddressDtls", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected AddressDtls addressDtls;
    @XmlElement(name = "Province_Of_Incorporation", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String provinceOfIncorporation;
    @XmlElement(name = "Business_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String businessId;
    @XmlElement(name = "Ref_Details", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ALOCCommon.xsd")
    protected List<RefDetails> refDetails;
    @XmlElement(name = "Principal_Bu_Unite_cd", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String principalBuUniteCd;
    @XmlElement(name = "Principal_Acc_Dist_No", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String principalAccDistNo;
    @XmlElement(name = "IBS_Syst_Msg", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String ibsSystMsg;
    @XmlElement(name = "IBS_Msg_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected BigInteger ibsMsgId;
    @XmlElement(name = "IBS_User_Sso", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String ibsUserSso;
    @XmlElement(name = "IBS_First_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String ibsFirstName;
    @XmlElement(name = "IBS_Last_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String ibsLastName;
    @XmlElement(name = "IBS_Phone_No", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String ibsPhoneNo;
    @XmlElement(name = "Comments", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String comments;
    @XmlElement(name = "Requires_Edits", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected Boolean requiresEdits;
    @XmlElement(name = "Send_Back_Notes", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String sendBackNotes;
    @XmlElement(name = "Change_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected String changeFlag;

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the leGoldId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeGoldId() {
        return leGoldId;
    }

    /**
     * Sets the value of the leGoldId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeGoldId(String value) {
        this.leGoldId = value;
    }

    /**
     * Gets the value of the leName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeName() {
        return leName;
    }

    /**
     * Sets the value of the leName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeName(String value) {
        this.leName = value;
    }

    /**
     * Gets the value of the principleInfoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipleInfoFlag() {
        return principleInfoFlag;
    }

    /**
     * Sets the value of the principleInfoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipleInfoFlag(String value) {
        this.principleInfoFlag = value;
    }

    /**
     * Gets the value of the geDivisionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeDivisionName() {
        return geDivisionName;
    }

    /**
     * Sets the value of the geDivisionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeDivisionName(String value) {
        this.geDivisionName = value;
    }

    /**
     * Gets the value of the geDivisionId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGeDivisionId() {
        return geDivisionId;
    }

    /**
     * Sets the value of the geDivisionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGeDivisionId(BigInteger value) {
        this.geDivisionId = value;
    }

    /**
     * Gets the value of the addressDtls property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDtls }
     *     
     */
    public AddressDtls getAddressDtls() {
        return addressDtls;
    }

    /**
     * Sets the value of the addressDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDtls }
     *     
     */
    public void setAddressDtls(AddressDtls value) {
        this.addressDtls = value;
    }

    /**
     * Gets the value of the provinceOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceOfIncorporation() {
        return provinceOfIncorporation;
    }

    /**
     * Sets the value of the provinceOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceOfIncorporation(String value) {
        this.provinceOfIncorporation = value;
    }

    /**
     * Gets the value of the businessId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * Sets the value of the businessId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessId(String value) {
        this.businessId = value;
    }

    /**
     * Gets the value of the refDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefDetails }
     * 
     * 
     */
    public List<RefDetails> getRefDetails() {
        if (refDetails == null) {
            refDetails = new ArrayList<RefDetails>();
        }
        return this.refDetails;
    }

    /**
     * Gets the value of the principalBuUniteCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalBuUniteCd() {
        return principalBuUniteCd;
    }

    /**
     * Sets the value of the principalBuUniteCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalBuUniteCd(String value) {
        this.principalBuUniteCd = value;
    }

    /**
     * Gets the value of the principalAccDistNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalAccDistNo() {
        return principalAccDistNo;
    }

    /**
     * Sets the value of the principalAccDistNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalAccDistNo(String value) {
        this.principalAccDistNo = value;
    }

    /**
     * Gets the value of the ibsSystMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBSSystMsg() {
        return ibsSystMsg;
    }

    /**
     * Sets the value of the ibsSystMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBSSystMsg(String value) {
        this.ibsSystMsg = value;
    }

    /**
     * Gets the value of the ibsMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIBSMsgId() {
        return ibsMsgId;
    }

    /**
     * Sets the value of the ibsMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIBSMsgId(BigInteger value) {
        this.ibsMsgId = value;
    }

    /**
     * Gets the value of the ibsUserSso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBSUserSso() {
        return ibsUserSso;
    }

    /**
     * Sets the value of the ibsUserSso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBSUserSso(String value) {
        this.ibsUserSso = value;
    }

    /**
     * Gets the value of the ibsFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBSFirstName() {
        return ibsFirstName;
    }

    /**
     * Sets the value of the ibsFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBSFirstName(String value) {
        this.ibsFirstName = value;
    }

    /**
     * Gets the value of the ibsLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBSLastName() {
        return ibsLastName;
    }

    /**
     * Sets the value of the ibsLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBSLastName(String value) {
        this.ibsLastName = value;
    }

    /**
     * Gets the value of the ibsPhoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBSPhoneNo() {
        return ibsPhoneNo;
    }

    /**
     * Sets the value of the ibsPhoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBSPhoneNo(String value) {
        this.ibsPhoneNo = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the requiresEdits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresEdits() {
        return requiresEdits;
    }

    /**
     * Sets the value of the requiresEdits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresEdits(Boolean value) {
        this.requiresEdits = value;
    }

    /**
     * Gets the value of the sendBackNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendBackNotes() {
        return sendBackNotes;
    }

    /**
     * Sets the value of the sendBackNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendBackNotes(String value) {
        this.sendBackNotes = value;
    }

    /**
     * Gets the value of the changeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeFlag() {
        return changeFlag;
    }

    /**
     * Sets the value of the changeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeFlag(String value) {
        this.changeFlag = value;
    }

    public Principal withOpCode(String value) {
        setOpCode(value);
        return this;
    }

    public Principal withLeGoldId(String value) {
        setLeGoldId(value);
        return this;
    }

    public Principal withLeName(String value) {
        setLeName(value);
        return this;
    }

    public Principal withPrincipleInfoFlag(String value) {
        setPrincipleInfoFlag(value);
        return this;
    }

    public Principal withGeDivisionName(String value) {
        setGeDivisionName(value);
        return this;
    }

    public Principal withGeDivisionId(BigInteger value) {
        setGeDivisionId(value);
        return this;
    }

    public Principal withAddressDtls(AddressDtls value) {
        setAddressDtls(value);
        return this;
    }

    public Principal withProvinceOfIncorporation(String value) {
        setProvinceOfIncorporation(value);
        return this;
    }

    public Principal withBusinessId(String value) {
        setBusinessId(value);
        return this;
    }

    public Principal withRefDetails(RefDetails... values) {
        if (values!= null) {
            for (RefDetails value: values) {
                getRefDetails().add(value);
            }
        }
        return this;
    }

    public Principal withRefDetails(Collection<RefDetails> values) {
        if (values!= null) {
            getRefDetails().addAll(values);
        }
        return this;
    }

    public Principal withPrincipalBuUniteCd(String value) {
        setPrincipalBuUniteCd(value);
        return this;
    }

    public Principal withPrincipalAccDistNo(String value) {
        setPrincipalAccDistNo(value);
        return this;
    }

    public Principal withIBSSystMsg(String value) {
        setIBSSystMsg(value);
        return this;
    }

    public Principal withIBSMsgId(BigInteger value) {
        setIBSMsgId(value);
        return this;
    }

    public Principal withIBSUserSso(String value) {
        setIBSUserSso(value);
        return this;
    }

    public Principal withIBSFirstName(String value) {
        setIBSFirstName(value);
        return this;
    }

    public Principal withIBSLastName(String value) {
        setIBSLastName(value);
        return this;
    }

    public Principal withIBSPhoneNo(String value) {
        setIBSPhoneNo(value);
        return this;
    }

    public Principal withComments(String value) {
        setComments(value);
        return this;
    }

    public Principal withRequiresEdits(Boolean value) {
        setRequiresEdits(value);
        return this;
    }

    public Principal withSendBackNotes(String value) {
        setSendBackNotes(value);
        return this;
    }

    public Principal withChangeFlag(String value) {
        setChangeFlag(value);
        return this;
    }

    /**
     * Sets the value of the refDetails property.
     * 
     * @param refDetails
     *     allowed object is
     *     {@link RefDetails }
     *     
     */
    public void setRefDetails(List<RefDetails> refDetails) {
        this.refDetails = refDetails;
    }

}
