//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/MsgHeader.xsd}Msg_Header" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/AgingDetails.xsd}AgingDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd}BidSuccessDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/ContingentliabilityDetails.xsd}ContingentliabilityDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/CycleTimeDetails.xsd}CycleTimeDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/ECSODetails.xsd}ECSODetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/FeesPaidDetails.xsd}FeesPaidDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/GCFODetails.xsd}GCFODetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/IssuanceExpirationDetails.xsd}IssuanceExpirationDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/UserReportDetails.xsd}UserReportDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/FeeQuotationDetails.xsd}FeeQuotationDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/AverageFeesPaidDetails.xsd}AverageFeesPaidDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Reports/FeeProjectionDetails.xsd}FeeProjectionDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgHeader",
    "agingDetails",
    "bidSuccessDetails",
    "contingentliabilityDetails",
    "cycleTimeDetails",
    "ecsoDetails",
    "feesPaidDetails",
    "gcfoDetails",
    "issuanceExpirationDetails",
    "userReportDetails",
    "feeQuotationDetails",
    "averageFeesPaidDetails",
    "feeProjectionDetails"
})
@XmlRootElement(name = "ReportsDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/ReportsDetails.xsd")
public class ReportsDetails
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Msg_Header", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/MsgHeader.xsd")
    protected MsgHeader msgHeader;
    @XmlElement(name = "AgingDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/AgingDetails.xsd")
    protected List<AgingDetails> agingDetails;
    @XmlElement(name = "BidSuccessDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/BidSuccessDetails.xsd")
    protected List<BidSuccessDetails> bidSuccessDetails;
    @XmlElement(name = "ContingentliabilityDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/ContingentliabilityDetails.xsd")
    protected List<ContingentliabilityDetails> contingentliabilityDetails;
    @XmlElement(name = "CycleTimeDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/CycleTimeDetails.xsd")
    protected List<CycleTimeDetails> cycleTimeDetails;
    @XmlElement(name = "ECSODetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/ECSODetails.xsd")
    protected List<ECSODetails> ecsoDetails;
    @XmlElement(name = "FeesPaidDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/FeesPaidDetails.xsd")
    protected List<FeesPaidDetails> feesPaidDetails;
    @XmlElement(name = "GCFODetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/GCFODetails.xsd")
    protected List<GCFODetails> gcfoDetails;
    @XmlElement(name = "IssuanceExpirationDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/IssuanceExpirationDetails.xsd")
    protected List<IssuanceExpirationDetails> issuanceExpirationDetails;
    @XmlElement(name = "UserReportDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/UserReportDetails.xsd")
    protected List<UserReportDetails> userReportDetails;
    @XmlElement(name = "FeeQuotationDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/FeeQuotationDetails.xsd")
    protected List<FeeQuotationDetails> feeQuotationDetails;
    @XmlElement(name = "AverageFeesPaidDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/AverageFeesPaidDetails.xsd")
    protected List<AverageFeesPaidDetails> averageFeesPaidDetails;
    @XmlElement(name = "FeeProjectionDetails", namespace = "http://treasury.ge.com/schemas/ALOC/Reports/FeeProjectionDetails.xsd")
    protected List<FeeProjectionDetails> feeProjectionDetails;

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    /**
     * Gets the value of the agingDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agingDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgingDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgingDetails }
     * 
     * 
     */
    public List<AgingDetails> getAgingDetails() {
        if (agingDetails == null) {
            agingDetails = new ArrayList<AgingDetails>();
        }
        return this.agingDetails;
    }

    /**
     * Gets the value of the bidSuccessDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bidSuccessDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBidSuccessDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BidSuccessDetails }
     * 
     * 
     */
    public List<BidSuccessDetails> getBidSuccessDetails() {
        if (bidSuccessDetails == null) {
            bidSuccessDetails = new ArrayList<BidSuccessDetails>();
        }
        return this.bidSuccessDetails;
    }

    /**
     * Gets the value of the contingentliabilityDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contingentliabilityDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContingentliabilityDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContingentliabilityDetails }
     * 
     * 
     */
    public List<ContingentliabilityDetails> getContingentliabilityDetails() {
        if (contingentliabilityDetails == null) {
            contingentliabilityDetails = new ArrayList<ContingentliabilityDetails>();
        }
        return this.contingentliabilityDetails;
    }

    /**
     * Gets the value of the cycleTimeDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cycleTimeDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCycleTimeDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CycleTimeDetails }
     * 
     * 
     */
    public List<CycleTimeDetails> getCycleTimeDetails() {
        if (cycleTimeDetails == null) {
            cycleTimeDetails = new ArrayList<CycleTimeDetails>();
        }
        return this.cycleTimeDetails;
    }

    /**
     * Gets the value of the ecsoDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ecsoDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getECSODetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ECSODetails }
     * 
     * 
     */
    public List<ECSODetails> getECSODetails() {
        if (ecsoDetails == null) {
            ecsoDetails = new ArrayList<ECSODetails>();
        }
        return this.ecsoDetails;
    }

    /**
     * Gets the value of the feesPaidDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feesPaidDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeesPaidDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeesPaidDetails }
     * 
     * 
     */
    public List<FeesPaidDetails> getFeesPaidDetails() {
        if (feesPaidDetails == null) {
            feesPaidDetails = new ArrayList<FeesPaidDetails>();
        }
        return this.feesPaidDetails;
    }

    /**
     * Gets the value of the gcfoDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gcfoDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGCFODetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GCFODetails }
     * 
     * 
     */
    public List<GCFODetails> getGCFODetails() {
        if (gcfoDetails == null) {
            gcfoDetails = new ArrayList<GCFODetails>();
        }
        return this.gcfoDetails;
    }

    /**
     * Gets the value of the issuanceExpirationDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issuanceExpirationDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssuanceExpirationDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssuanceExpirationDetails }
     * 
     * 
     */
    public List<IssuanceExpirationDetails> getIssuanceExpirationDetails() {
        if (issuanceExpirationDetails == null) {
            issuanceExpirationDetails = new ArrayList<IssuanceExpirationDetails>();
        }
        return this.issuanceExpirationDetails;
    }

    /**
     * Gets the value of the userReportDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userReportDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserReportDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserReportDetails }
     * 
     * 
     */
    public List<UserReportDetails> getUserReportDetails() {
        if (userReportDetails == null) {
            userReportDetails = new ArrayList<UserReportDetails>();
        }
        return this.userReportDetails;
    }

    /**
     * Gets the value of the feeQuotationDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feeQuotationDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeeQuotationDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeeQuotationDetails }
     * 
     * 
     */
    public List<FeeQuotationDetails> getFeeQuotationDetails() {
        if (feeQuotationDetails == null) {
            feeQuotationDetails = new ArrayList<FeeQuotationDetails>();
        }
        return this.feeQuotationDetails;
    }

    /**
     * Gets the value of the averageFeesPaidDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the averageFeesPaidDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAverageFeesPaidDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AverageFeesPaidDetails }
     * 
     * 
     */
    public List<AverageFeesPaidDetails> getAverageFeesPaidDetails() {
        if (averageFeesPaidDetails == null) {
            averageFeesPaidDetails = new ArrayList<AverageFeesPaidDetails>();
        }
        return this.averageFeesPaidDetails;
    }

    /**
     * Gets the value of the feeProjectionDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feeProjectionDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeeProjectionDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeeProjectionDetails }
     * 
     * 
     */
    public List<FeeProjectionDetails> getFeeProjectionDetails() {
        if (feeProjectionDetails == null) {
            feeProjectionDetails = new ArrayList<FeeProjectionDetails>();
        }
        return this.feeProjectionDetails;
    }

    public ReportsDetails withMsgHeader(MsgHeader value) {
        setMsgHeader(value);
        return this;
    }

    public ReportsDetails withAgingDetails(AgingDetails... values) {
        if (values!= null) {
            for (AgingDetails value: values) {
                getAgingDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withAgingDetails(Collection<AgingDetails> values) {
        if (values!= null) {
            getAgingDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withBidSuccessDetails(BidSuccessDetails... values) {
        if (values!= null) {
            for (BidSuccessDetails value: values) {
                getBidSuccessDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withBidSuccessDetails(Collection<BidSuccessDetails> values) {
        if (values!= null) {
            getBidSuccessDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withContingentliabilityDetails(ContingentliabilityDetails... values) {
        if (values!= null) {
            for (ContingentliabilityDetails value: values) {
                getContingentliabilityDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withContingentliabilityDetails(Collection<ContingentliabilityDetails> values) {
        if (values!= null) {
            getContingentliabilityDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withCycleTimeDetails(CycleTimeDetails... values) {
        if (values!= null) {
            for (CycleTimeDetails value: values) {
                getCycleTimeDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withCycleTimeDetails(Collection<CycleTimeDetails> values) {
        if (values!= null) {
            getCycleTimeDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withECSODetails(ECSODetails... values) {
        if (values!= null) {
            for (ECSODetails value: values) {
                getECSODetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withECSODetails(Collection<ECSODetails> values) {
        if (values!= null) {
            getECSODetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withFeesPaidDetails(FeesPaidDetails... values) {
        if (values!= null) {
            for (FeesPaidDetails value: values) {
                getFeesPaidDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withFeesPaidDetails(Collection<FeesPaidDetails> values) {
        if (values!= null) {
            getFeesPaidDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withGCFODetails(GCFODetails... values) {
        if (values!= null) {
            for (GCFODetails value: values) {
                getGCFODetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withGCFODetails(Collection<GCFODetails> values) {
        if (values!= null) {
            getGCFODetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withIssuanceExpirationDetails(IssuanceExpirationDetails... values) {
        if (values!= null) {
            for (IssuanceExpirationDetails value: values) {
                getIssuanceExpirationDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withIssuanceExpirationDetails(Collection<IssuanceExpirationDetails> values) {
        if (values!= null) {
            getIssuanceExpirationDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withUserReportDetails(UserReportDetails... values) {
        if (values!= null) {
            for (UserReportDetails value: values) {
                getUserReportDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withUserReportDetails(Collection<UserReportDetails> values) {
        if (values!= null) {
            getUserReportDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withFeeQuotationDetails(FeeQuotationDetails... values) {
        if (values!= null) {
            for (FeeQuotationDetails value: values) {
                getFeeQuotationDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withFeeQuotationDetails(Collection<FeeQuotationDetails> values) {
        if (values!= null) {
            getFeeQuotationDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withAverageFeesPaidDetails(AverageFeesPaidDetails... values) {
        if (values!= null) {
            for (AverageFeesPaidDetails value: values) {
                getAverageFeesPaidDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withAverageFeesPaidDetails(Collection<AverageFeesPaidDetails> values) {
        if (values!= null) {
            getAverageFeesPaidDetails().addAll(values);
        }
        return this;
    }

    public ReportsDetails withFeeProjectionDetails(FeeProjectionDetails... values) {
        if (values!= null) {
            for (FeeProjectionDetails value: values) {
                getFeeProjectionDetails().add(value);
            }
        }
        return this;
    }

    public ReportsDetails withFeeProjectionDetails(Collection<FeeProjectionDetails> values) {
        if (values!= null) {
            getFeeProjectionDetails().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the agingDetails property.
     * 
     * @param agingDetails
     *     allowed object is
     *     {@link AgingDetails }
     *     
     */
    public void setAgingDetails(List<AgingDetails> agingDetails) {
        this.agingDetails = agingDetails;
    }

    /**
     * Sets the value of the bidSuccessDetails property.
     * 
     * @param bidSuccessDetails
     *     allowed object is
     *     {@link BidSuccessDetails }
     *     
     */
    public void setBidSuccessDetails(List<BidSuccessDetails> bidSuccessDetails) {
        this.bidSuccessDetails = bidSuccessDetails;
    }

    /**
     * Sets the value of the contingentliabilityDetails property.
     * 
     * @param contingentliabilityDetails
     *     allowed object is
     *     {@link ContingentliabilityDetails }
     *     
     */
    public void setContingentliabilityDetails(List<ContingentliabilityDetails> contingentliabilityDetails) {
        this.contingentliabilityDetails = contingentliabilityDetails;
    }

    /**
     * Sets the value of the cycleTimeDetails property.
     * 
     * @param cycleTimeDetails
     *     allowed object is
     *     {@link CycleTimeDetails }
     *     
     */
    public void setCycleTimeDetails(List<CycleTimeDetails> cycleTimeDetails) {
        this.cycleTimeDetails = cycleTimeDetails;
    }

    /**
     * Sets the value of the ecsoDetails property.
     * 
     * @param ecsoDetails
     *     allowed object is
     *     {@link ECSODetails }
     *     
     */
    public void setECSODetails(List<ECSODetails> ecsoDetails) {
        this.ecsoDetails = ecsoDetails;
    }

    /**
     * Sets the value of the feesPaidDetails property.
     * 
     * @param feesPaidDetails
     *     allowed object is
     *     {@link FeesPaidDetails }
     *     
     */
    public void setFeesPaidDetails(List<FeesPaidDetails> feesPaidDetails) {
        this.feesPaidDetails = feesPaidDetails;
    }

    /**
     * Sets the value of the gcfoDetails property.
     * 
     * @param gcfoDetails
     *     allowed object is
     *     {@link GCFODetails }
     *     
     */
    public void setGCFODetails(List<GCFODetails> gcfoDetails) {
        this.gcfoDetails = gcfoDetails;
    }

    /**
     * Sets the value of the issuanceExpirationDetails property.
     * 
     * @param issuanceExpirationDetails
     *     allowed object is
     *     {@link IssuanceExpirationDetails }
     *     
     */
    public void setIssuanceExpirationDetails(List<IssuanceExpirationDetails> issuanceExpirationDetails) {
        this.issuanceExpirationDetails = issuanceExpirationDetails;
    }

    /**
     * Sets the value of the userReportDetails property.
     * 
     * @param userReportDetails
     *     allowed object is
     *     {@link UserReportDetails }
     *     
     */
    public void setUserReportDetails(List<UserReportDetails> userReportDetails) {
        this.userReportDetails = userReportDetails;
    }

    /**
     * Sets the value of the feeQuotationDetails property.
     * 
     * @param feeQuotationDetails
     *     allowed object is
     *     {@link FeeQuotationDetails }
     *     
     */
    public void setFeeQuotationDetails(List<FeeQuotationDetails> feeQuotationDetails) {
        this.feeQuotationDetails = feeQuotationDetails;
    }

    /**
     * Sets the value of the averageFeesPaidDetails property.
     * 
     * @param averageFeesPaidDetails
     *     allowed object is
     *     {@link AverageFeesPaidDetails }
     *     
     */
    public void setAverageFeesPaidDetails(List<AverageFeesPaidDetails> averageFeesPaidDetails) {
        this.averageFeesPaidDetails = averageFeesPaidDetails;
    }

    /**
     * Sets the value of the feeProjectionDetails property.
     * 
     * @param feeProjectionDetails
     *     allowed object is
     *     {@link FeeProjectionDetails }
     *     
     */
    public void setFeeProjectionDetails(List<FeeProjectionDetails> feeProjectionDetails) {
        this.feeProjectionDetails = feeProjectionDetails;
    }

}
