//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Business_Site_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/MsgHeader.xsd}Msg_Header" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/Admin/RequestorLookUp.xsd}RequestorLookUp" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "businessSiteName",
    "msgHeader",
    "requestorLookUps"
})
@XmlRootElement(name = "RequestorSearchRequest", namespace = "http://treasury.ge.com/schemas/ALOC/Admin/RequestorSearhRequest.xsd")
public class RequestorSearchRequest
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Business_Site_Name", namespace = "http://treasury.ge.com/schemas/ALOC/Admin/RequestorSearhRequest.xsd")
    protected String businessSiteName;
    @XmlElement(name = "Msg_Header", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/MsgHeader.xsd")
    protected MsgHeader msgHeader;
    @XmlElement(name = "RequestorLookUp", namespace = "http://treasury.ge.com/schemas/ALOC/Admin/RequestorLookUp.xsd")
    protected List<RequestorLookUp> requestorLookUps;

    /**
     * Gets the value of the businessSiteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessSiteName() {
        return businessSiteName;
    }

    /**
     * Sets the value of the businessSiteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessSiteName(String value) {
        this.businessSiteName = value;
    }

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    /**
     * Gets the value of the requestorLookUps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestorLookUps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestorLookUps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestorLookUp }
     * 
     * 
     */
    public List<RequestorLookUp> getRequestorLookUps() {
        if (requestorLookUps == null) {
            requestorLookUps = new ArrayList<RequestorLookUp>();
        }
        return this.requestorLookUps;
    }

    public RequestorSearchRequest withBusinessSiteName(String value) {
        setBusinessSiteName(value);
        return this;
    }

    public RequestorSearchRequest withMsgHeader(MsgHeader value) {
        setMsgHeader(value);
        return this;
    }

    public RequestorSearchRequest withRequestorLookUps(RequestorLookUp... values) {
        if (values!= null) {
            for (RequestorLookUp value: values) {
                getRequestorLookUps().add(value);
            }
        }
        return this;
    }

    public RequestorSearchRequest withRequestorLookUps(Collection<RequestorLookUp> values) {
        if (values!= null) {
            getRequestorLookUps().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the requestorLookUps property.
     * 
     * @param requestorLookUps
     *     allowed object is
     *     {@link RequestorLookUp }
     *     
     */
    public void setRequestorLookUps(List<RequestorLookUp> requestorLookUps) {
        this.requestorLookUps = requestorLookUps;
    }

}
