//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 12:40:24 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for Rider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Op_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Request_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Bank_Reference_Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rider_Request_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Instrument_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Instrument_Type_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Trigger_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd}Principal" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/Obligee.xsd}Obligee" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd}ExpiryDate" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/RiderBondInformation.xsd}RiderBondInformation" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/Attachments.xsd}Attachment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd}DeliveryInstructions" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/ALOCCommon.xsd}ActionDetails" minOccurs="0"/>
 *         &lt;element name="Rider_Workflow_Amt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rider", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd", propOrder = {
    "opCode",
    "requestId",
    "bankReferenceNumber",
    "riderRequestId",
    "instrumentType",
    "instrumentTypeId",
    "triggerType",
    "principal",
    "obligee",
    "expiryDate",
    "riderBondInformation",
    "attachments",
    "deliveryInstructions",
    "actionDetails",
    "riderWorkflowAmt"
})
public class Rider
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Op_Code", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected String opCode;
    @XmlElement(name = "Request_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected BigInteger requestId;
    @XmlElement(name = "Bank_Reference_Number", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected String bankReferenceNumber;
    @XmlElement(name = "Rider_Request_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected String riderRequestId;
    @XmlElement(name = "Instrument_Type", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected String instrumentType;
    @XmlElement(name = "Instrument_Type_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected String instrumentTypeId;
    @XmlElement(name = "Trigger_Type", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected String triggerType;
    @XmlElement(name = "Principal", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Principal.xsd")
    protected Principal principal;
    @XmlElement(name = "Obligee", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Obligee.xsd")
    protected Obligee obligee;
    @XmlElement(name = "ExpiryDate", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd")
    protected ExpiryDate expiryDate;
    @XmlElement(name = "RiderBondInformation", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/RiderBondInformation.xsd")
    protected RiderBondInformation riderBondInformation;
    @XmlElement(name = "Attachment", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Attachments.xsd")
    protected List<Attachment> attachments;
    @XmlElement(name = "DeliveryInstructions", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DeliveryInstructions.xsd")
    protected DeliveryInstructions deliveryInstructions;
    @XmlElement(name = "ActionDetails", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ALOCCommon.xsd")
    protected ActionDetails actionDetails;
    @XmlElement(name = "Rider_Workflow_Amt", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/Rider.xsd")
    protected BigDecimal riderWorkflowAmt;

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestId(BigInteger value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the bankReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankReferenceNumber() {
        return bankReferenceNumber;
    }

    /**
     * Sets the value of the bankReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankReferenceNumber(String value) {
        this.bankReferenceNumber = value;
    }

    /**
     * Gets the value of the riderRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiderRequestId() {
        return riderRequestId;
    }

    /**
     * Sets the value of the riderRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiderRequestId(String value) {
        this.riderRequestId = value;
    }

    /**
     * Gets the value of the instrumentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentType() {
        return instrumentType;
    }

    /**
     * Sets the value of the instrumentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentType(String value) {
        this.instrumentType = value;
    }

    /**
     * Gets the value of the instrumentTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentTypeId() {
        return instrumentTypeId;
    }

    /**
     * Sets the value of the instrumentTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentTypeId(String value) {
        this.instrumentTypeId = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerType(String value) {
        this.triggerType = value;
    }

    /**
     * Gets the value of the principal property.
     * 
     * @return
     *     possible object is
     *     {@link Principal }
     *     
     */
    public Principal getPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Principal }
     *     
     */
    public void setPrincipal(Principal value) {
        this.principal = value;
    }

    /**
     * Gets the value of the obligee property.
     * 
     * @return
     *     possible object is
     *     {@link Obligee }
     *     
     */
    public Obligee getObligee() {
        return obligee;
    }

    /**
     * Sets the value of the obligee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obligee }
     *     
     */
    public void setObligee(Obligee value) {
        this.obligee = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link ExpiryDate }
     *     
     */
    public ExpiryDate getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpiryDate }
     *     
     */
    public void setExpiryDate(ExpiryDate value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the riderBondInformation property.
     * 
     * @return
     *     possible object is
     *     {@link RiderBondInformation }
     *     
     */
    public RiderBondInformation getRiderBondInformation() {
        return riderBondInformation;
    }

    /**
     * Sets the value of the riderBondInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiderBondInformation }
     *     
     */
    public void setRiderBondInformation(RiderBondInformation value) {
        this.riderBondInformation = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attachment }
     * 
     * 
     */
    public List<Attachment> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<Attachment>();
        }
        return this.attachments;
    }

    /**
     * Gets the value of the deliveryInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryInstructions }
     *     
     */
    public DeliveryInstructions getDeliveryInstructions() {
        return deliveryInstructions;
    }

    /**
     * Sets the value of the deliveryInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryInstructions }
     *     
     */
    public void setDeliveryInstructions(DeliveryInstructions value) {
        this.deliveryInstructions = value;
    }

    /**
     * Gets the value of the actionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ActionDetails }
     *     
     */
    public ActionDetails getActionDetails() {
        return actionDetails;
    }

    /**
     * Sets the value of the actionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionDetails }
     *     
     */
    public void setActionDetails(ActionDetails value) {
        this.actionDetails = value;
    }

    /**
     * Gets the value of the riderWorkflowAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRiderWorkflowAmt() {
        return riderWorkflowAmt;
    }

    /**
     * Sets the value of the riderWorkflowAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRiderWorkflowAmt(BigDecimal value) {
        this.riderWorkflowAmt = value;
    }

    public Rider withOpCode(String value) {
        setOpCode(value);
        return this;
    }

    public Rider withRequestId(BigInteger value) {
        setRequestId(value);
        return this;
    }

    public Rider withBankReferenceNumber(String value) {
        setBankReferenceNumber(value);
        return this;
    }

    public Rider withRiderRequestId(String value) {
        setRiderRequestId(value);
        return this;
    }

    public Rider withInstrumentType(String value) {
        setInstrumentType(value);
        return this;
    }

    public Rider withInstrumentTypeId(String value) {
        setInstrumentTypeId(value);
        return this;
    }

    public Rider withTriggerType(String value) {
        setTriggerType(value);
        return this;
    }

    public Rider withPrincipal(Principal value) {
        setPrincipal(value);
        return this;
    }

    public Rider withObligee(Obligee value) {
        setObligee(value);
        return this;
    }

    public Rider withExpiryDate(ExpiryDate value) {
        setExpiryDate(value);
        return this;
    }

    public Rider withRiderBondInformation(RiderBondInformation value) {
        setRiderBondInformation(value);
        return this;
    }

    public Rider withAttachments(Attachment... values) {
        if (values!= null) {
            for (Attachment value: values) {
                getAttachments().add(value);
            }
        }
        return this;
    }

    public Rider withAttachments(Collection<Attachment> values) {
        if (values!= null) {
            getAttachments().addAll(values);
        }
        return this;
    }

    public Rider withDeliveryInstructions(DeliveryInstructions value) {
        setDeliveryInstructions(value);
        return this;
    }

    public Rider withActionDetails(ActionDetails value) {
        setActionDetails(value);
        return this;
    }

    public Rider withRiderWorkflowAmt(BigDecimal value) {
        setRiderWorkflowAmt(value);
        return this;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param attachments
     *     allowed object is
     *     {@link Attachment }
     *     
     */
    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }

}
