/**
 * 
 */
$(document).ready(function() {
	$('#navTab1').click(function(){
		$('#notSureAboutInstrumentID').val(false);
		$('#2').find('input[type=radio]').attr('checked',false);
	});
	$('#navTab2').click(function(){
		$('#notSureAboutInstrumentID').val(true);
		$("#inside").find(".radio-container").show();
		$("#inside").find(".label-container").hide();
		$("#inside").hide();
		$("#outside").find(".radio-container").show();
		$("#outside").find(".label-container").hide();
		$("#outside").hide();
		$("#ins").show();
		$('#2').find('input[type=radio]').attr('checked',false);
	});
	$('.reqclose').click(function(){
		$('.siteError').hide();
		$('.siteError').parent('div').removeClass('errorBlock');
		$('.instrumentError').hide();
		$('.instrumentError').parent('div').removeClass('errorBlock');
		$('#2').find('input[type=radio]').attr('checked',false);
	});
	$('input.createRequest').click(function(){
		$('.siteError').hide();
		$('.instrumentError').hide();
		var errorFlag = 0;
		if($('#selectSite :selected').val() == -1){
			$('.siteError').show();
			$('.siteError').parent('div').addClass('errorBlock');
			errorFlag = 1;
		}else{
			$('.siteError').hide();
			$('.siteError').parent('div').removeClass('errorBlock');
		}
		if($('#notSureAboutInstrumentID').val() == 'false'){
			if($('#selectInstrument :selected').val() == -1){
				$('.instrumentError').show();
				$('.instrumentError').parent('div').addClass('errorBlock');
				errorFlag = 1;
			}else{
				$('.instrumentError').hide();
				$('.instrumentError').parent('div').removeClass('errorBlock');
			}
		}
		if(errorFlag == 1){
			return false;
		}
	});
	
	$("#instrumentIssuedRegion_insideUS").click(function(){
        $("#inside").show();
		   $("#outside").hide();
		   $("#ins").hide();
     });
	$("#instrumentIssuedRegion_outsideUS").click(function(){
			$("#inside").hide();
        $("#outside").show();
		    $("#ins").hide();
     });
	$("#instrumentGoverningRules_practice").click(function(){
			$("#gov").hide();
			$("#ucp").show();
        $("#urdg").hide();
     });
	$("#instrumentGoverningRules_guarantee").click(function(){
			$("#gov").hide();
			$("#ucp").hide();
        $("#urdg").show();
     });
	$("#instrumentGoverningRules_customs").click(function(){
			$("#govern").hide();
			$("#customUcp").show();
        $("#demandUrdg").hide();
		   $("#unk").hide();
     });
	$("#instrumentGoverningRules_demand").click(function(){
			$("#govern").hide();
			$("#customUcp").hide();
        $("#demandUrdg").show();
		   $("#unk").hide();
     });
	$("#instrumentGoverningRules_unknown").click(function(){
			$("#govern").hide();
			$("#customUcp").hide();
        $("#demandUrdg").hide();
		   $("#unk").show();
     });
	$("#customs_subjectToLocalCountryLaws_yes").click(function(){
			$("#local").hide();
			$("#localYes").show();
        $("#localNo").hide();
     });
	$("#customs_subjectToLocalCountryLaws_no").click(function(){
			$("#local").hide();
			$("#localYes").hide();
        $("#localNo").show();
     });
	$("#demand_subjectToLocalCountryLaws_yes").change(function(){
			$("#localaws").hide();
			$("#localawsYes").show();
        $("#localawsNo").hide();
     });
	$("#demand_subjectToLocalCountryLaws_no").change(function(){
			$("#localaws").hide();
			$("#localawsYes").hide();
        $("#localawsNo").show();
     });
	$("#unknown_subjectToLocalCountryLaws_yes").change(function(){
			$("#lcl").hide();
			$("#lclYes").show();
        $("#lclNo").hide();
     });
	$("#unknown_subjectToLocalCountryLaws_no").change(function(){
			$("#lcl").hide();
			$("#lclYes").hide();
        $("#lclNo").show();
     });
	$("#customs_yes_textFormatRefer_sloc").change(function(){
			$("#refer").hide();
			$("#standbyLoc").show();
        $("#bankg").hide();
     });
	$("#customs_yes_textFormatRefer_bg").change(function(){
			$("#refer").hide();
			$("#standbyLoc").hide();
        $("#bankg").show();
     });
	$("#customs_no_textFormatRefer_sloc").change(function(){
			$("#formatRefer").hide();
			$("#standby1").show();
        $("#bank1").hide();
     });
	$("#customs_no_textFormatRefer_bg").change(function(){
			$("#formatRefer").hide();
			$("#standby1").hide();
        $("#bank1").show();
     });
	$("#unknown_yes_textFormatRefer_sloc").change(function(){
			$("#forrefer").hide();
			$("#standbyLetoc").show();
        $("#bankguar").hide();
     });
	$("#unknown_yes_textFormatRefer_bg").change(function(){
			$("#forrefer").hide();
			$("#standbyLetoc").hide();
        $("#bankguar").show();
     });
	$("#demand_no_textFormatRefer_sloc").change(function(){
			$("#formatRef").hide();
			$("#standby2").show();
        $("#bank2").hide();
     });
	$("#demand_no_textFormatRefer_bg").change(function(){
			$("#formatRef").hide();
			$("#standby2").hide();
        $("#bank2").show();
     });
	$("#unknown_no_textFormatRefer_sloc").change(function(){
			$("#formRefer").hide();
			$("#standby3").show();
        $("#bank3").hide();
     });
	$("#unknown_no_textFormatRefer_bg").change(function(){
			$("#formRefer").hide();
			$("#standby3").hide();
        $("#bank3").show();
     });
	
});