//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.08 at 07:56:29 PM IST 
//


package com.ge.icfp.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.hydus.wff.core.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Delegate_Opcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Role_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Role_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="User_Delegate_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Delegator_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delegate_SSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delegate_From_Dt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Delegate_To_Dt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Actual_Delegate_End_Dt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Delegator_Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delegator_First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delete_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delegate_Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delegate_First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ICFP/MsgHeader.xsd}Msg_Header" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "delegateOpcode",
    "roleId",
    "roleName",
    "userDelegateId",
    "delegatorSSO",
    "delegateSSO",
    "delegateFromDt",
    "delegateToDt",
    "actualDelegateEndDt",
    "delegatorLastName",
    "delegatorFirstName",
    "deleteFlag",
    "delegateLastName",
    "delegateFirstName",
    "status",
    "msgHeader"
})
@XmlRootElement(name = "Delegation", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
public class Delegation
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Delegate_Opcode", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegateOpcode;
    @XmlElement(name = "Role_Id", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected Integer roleId;
    @XmlElement(name = "Role_Name", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String roleName;
    @XmlElement(name = "User_Delegate_Id", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected Integer userDelegateId;
    @XmlElement(name = "Delegator_SSO", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegatorSSO;
    @XmlElement(name = "Delegate_SSO", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegateSSO;
    @XmlElement(name = "Delegate_From_Dt", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected XMLGregorianCalendar delegateFromDt;
    @XmlElement(name = "Delegate_To_Dt", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected XMLGregorianCalendar delegateToDt;
    @XmlElement(name = "Actual_Delegate_End_Dt", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected XMLGregorianCalendar actualDelegateEndDt;
    @XmlElement(name = "Delegator_Last_Name", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegatorLastName;
    @XmlElement(name = "Delegator_First_Name", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegatorFirstName;
    @XmlElement(name = "Delete_Flag", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String deleteFlag;
    @XmlElement(name = "Delegate_Last_Name", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegateLastName;
    @XmlElement(name = "Delegate_First_Name", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String delegateFirstName;
    @XmlElement(name = "Status", namespace = "http://treasury.ge.com/schemas/ICFP/Delegation.xsd")
    protected String status;
    @XmlElement(name = "Msg_Header", namespace = "http://treasury.ge.com/schemas/ICFP/MsgHeader.xsd")
    protected MsgHeader msgHeader;

    /**
     * Gets the value of the delegateOpcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateOpcode() {
        return delegateOpcode;
    }

    /**
     * Sets the value of the delegateOpcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateOpcode(String value) {
        this.delegateOpcode = value;
    }

    /**
     * Gets the value of the roleId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * Sets the value of the roleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRoleId(Integer value) {
        this.roleId = value;
    }

    /**
     * Gets the value of the roleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * Sets the value of the roleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleName(String value) {
        this.roleName = value;
    }

    /**
     * Gets the value of the userDelegateId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUserDelegateId() {
        return userDelegateId;
    }

    /**
     * Sets the value of the userDelegateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUserDelegateId(Integer value) {
        this.userDelegateId = value;
    }

    /**
     * Gets the value of the delegatorSSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegatorSSO() {
        return delegatorSSO;
    }

    /**
     * Sets the value of the delegatorSSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegatorSSO(String value) {
        this.delegatorSSO = value;
    }

    /**
     * Gets the value of the delegateSSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateSSO() {
        return delegateSSO;
    }

    /**
     * Sets the value of the delegateSSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateSSO(String value) {
        this.delegateSSO = value;
    }

    /**
     * Gets the value of the delegateFromDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDelegateFromDt() {
        return delegateFromDt;
    }

    /**
     * Sets the value of the delegateFromDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDelegateFromDt(XMLGregorianCalendar value) {
        this.delegateFromDt = value;
    }

    /**
     * Gets the value of the delegateToDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDelegateToDt() {
        return delegateToDt;
    }

    /**
     * Sets the value of the delegateToDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDelegateToDt(XMLGregorianCalendar value) {
        this.delegateToDt = value;
    }

    /**
     * Gets the value of the actualDelegateEndDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualDelegateEndDt() {
        return actualDelegateEndDt;
    }

    /**
     * Sets the value of the actualDelegateEndDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualDelegateEndDt(XMLGregorianCalendar value) {
        this.actualDelegateEndDt = value;
    }

    /**
     * Gets the value of the delegatorLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegatorLastName() {
        return delegatorLastName;
    }

    /**
     * Sets the value of the delegatorLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegatorLastName(String value) {
        this.delegatorLastName = value;
    }

    /**
     * Gets the value of the delegatorFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegatorFirstName() {
        return delegatorFirstName;
    }

    /**
     * Sets the value of the delegatorFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegatorFirstName(String value) {
        this.delegatorFirstName = value;
    }

    /**
     * Gets the value of the deleteFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * Sets the value of the deleteFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteFlag(String value) {
        this.deleteFlag = value;
    }

    /**
     * Gets the value of the delegateLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateLastName() {
        return delegateLastName;
    }

    /**
     * Sets the value of the delegateLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateLastName(String value) {
        this.delegateLastName = value;
    }

    /**
     * Gets the value of the delegateFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateFirstName() {
        return delegateFirstName;
    }

    /**
     * Sets the value of the delegateFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateFirstName(String value) {
        this.delegateFirstName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    public Delegation withDelegateOpcode(String value) {
        setDelegateOpcode(value);
        return this;
    }

    public Delegation withRoleId(Integer value) {
        setRoleId(value);
        return this;
    }

    public Delegation withRoleName(String value) {
        setRoleName(value);
        return this;
    }

    public Delegation withUserDelegateId(Integer value) {
        setUserDelegateId(value);
        return this;
    }

    public Delegation withDelegatorSSO(String value) {
        setDelegatorSSO(value);
        return this;
    }

    public Delegation withDelegateSSO(String value) {
        setDelegateSSO(value);
        return this;
    }

    public Delegation withDelegateFromDt(XMLGregorianCalendar value) {
        setDelegateFromDt(value);
        return this;
    }

    public Delegation withDelegateToDt(XMLGregorianCalendar value) {
        setDelegateToDt(value);
        return this;
    }

    public Delegation withActualDelegateEndDt(XMLGregorianCalendar value) {
        setActualDelegateEndDt(value);
        return this;
    }

    public Delegation withDelegatorLastName(String value) {
        setDelegatorLastName(value);
        return this;
    }

    public Delegation withDelegatorFirstName(String value) {
        setDelegatorFirstName(value);
        return this;
    }

    public Delegation withDeleteFlag(String value) {
        setDeleteFlag(value);
        return this;
    }

    public Delegation withDelegateLastName(String value) {
        setDelegateLastName(value);
        return this;
    }

    public Delegation withDelegateFirstName(String value) {
        setDelegateFirstName(value);
        return this;
    }

    public Delegation withStatus(String value) {
        setStatus(value);
        return this;
    }

    public Delegation withMsgHeader(MsgHeader value) {
        setMsgHeader(value);
        return this;
    }

}
