//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.08 at 07:56:29 PM IST 
//


package com.ge.icfp.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.wff.core.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Interest_Type_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Day_Count_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Floating_Rate_Index" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Floating_Rate_Index_Term" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Index_Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Min_Spread" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Max_Spread" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Spread" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Base_Fixed_Rate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interestTypeId",
    "dayCountId",
    "floatingRateIndex",
    "floatingRateIndexTerm",
    "indexSource",
    "minSpread",
    "maxSpread",
    "spread",
    "baseFixedRate"
})
@XmlRootElement(name = "Rate_Information", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
public class RateInformation
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Interest_Type_Id", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected Integer interestTypeId;
    @XmlElement(name = "Day_Count_Id", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected Integer dayCountId;
    @XmlElement(name = "Floating_Rate_Index", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected String floatingRateIndex;
    @XmlElement(name = "Floating_Rate_Index_Term", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected String floatingRateIndexTerm;
    @XmlElement(name = "Index_Source", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected String indexSource;
    @XmlElement(name = "Min_Spread", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected Double minSpread;
    @XmlElement(name = "Max_Spread", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected Double maxSpread;
    @XmlElement(name = "Spread", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected Double spread;
    @XmlElement(name = "Base_Fixed_Rate", namespace = "http://treasury.ge.com/schemas/ICFP/RateInformation.xsd")
    protected Double baseFixedRate;

    /**
     * Gets the value of the interestTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInterestTypeId() {
        return interestTypeId;
    }

    /**
     * Sets the value of the interestTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInterestTypeId(Integer value) {
        this.interestTypeId = value;
    }

    /**
     * Gets the value of the dayCountId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDayCountId() {
        return dayCountId;
    }

    /**
     * Sets the value of the dayCountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDayCountId(Integer value) {
        this.dayCountId = value;
    }

    /**
     * Gets the value of the floatingRateIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloatingRateIndex() {
        return floatingRateIndex;
    }

    /**
     * Sets the value of the floatingRateIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloatingRateIndex(String value) {
        this.floatingRateIndex = value;
    }

    /**
     * Gets the value of the floatingRateIndexTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloatingRateIndexTerm() {
        return floatingRateIndexTerm;
    }

    /**
     * Sets the value of the floatingRateIndexTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloatingRateIndexTerm(String value) {
        this.floatingRateIndexTerm = value;
    }

    /**
     * Gets the value of the indexSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexSource() {
        return indexSource;
    }

    /**
     * Sets the value of the indexSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexSource(String value) {
        this.indexSource = value;
    }

    /**
     * Gets the value of the minSpread property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinSpread() {
        return minSpread;
    }

    /**
     * Sets the value of the minSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinSpread(Double value) {
        this.minSpread = value;
    }

    /**
     * Gets the value of the maxSpread property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxSpread() {
        return maxSpread;
    }

    /**
     * Sets the value of the maxSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxSpread(Double value) {
        this.maxSpread = value;
    }

    /**
     * Gets the value of the spread property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpread() {
        return spread;
    }

    /**
     * Sets the value of the spread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpread(Double value) {
        this.spread = value;
    }

    /**
     * Gets the value of the baseFixedRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBaseFixedRate() {
        return baseFixedRate;
    }

    /**
     * Sets the value of the baseFixedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBaseFixedRate(Double value) {
        this.baseFixedRate = value;
    }

    public RateInformation withInterestTypeId(Integer value) {
        setInterestTypeId(value);
        return this;
    }

    public RateInformation withDayCountId(Integer value) {
        setDayCountId(value);
        return this;
    }

    public RateInformation withFloatingRateIndex(String value) {
        setFloatingRateIndex(value);
        return this;
    }

    public RateInformation withFloatingRateIndexTerm(String value) {
        setFloatingRateIndexTerm(value);
        return this;
    }

    public RateInformation withIndexSource(String value) {
        setIndexSource(value);
        return this;
    }

    public RateInformation withMinSpread(Double value) {
        setMinSpread(value);
        return this;
    }

    public RateInformation withMaxSpread(Double value) {
        setMaxSpread(value);
        return this;
    }

    public RateInformation withSpread(Double value) {
        setSpread(value);
        return this;
    }

    public RateInformation withBaseFixedRate(Double value) {
        setBaseFixedRate(value);
        return this;
    }

}
