//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 10:39:33 AM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.hydus.hwf.jaxb.adapters.XMLDatetimeAsCalendarAdapter;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Aloc_Record_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Field_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Old_Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="New_Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Audit_Creator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Audit_Created_Dt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Author_First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Author_Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Transaction_Complete_Dt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Amendment_Rider_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Agreement_Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Update_Reporting_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reason_For_Change" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "alocRecordId",
    "fieldName",
    "oldValue",
    "newValue",
    "auditCreator",
    "auditCreatedDt",
    "author",
    "authorFirstName",
    "authorLastName",
    "transactionCompleteDt",
    "amendmentRiderId",
    "agreementId",
    "updateReportingFlag",
    "reasonForChange"
})
@XmlRootElement(name = "Audit_Log", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
public class AuditLog
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Request_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected BigInteger requestId;
    @XmlElement(name = "Aloc_Record_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String alocRecordId;
    @XmlElement(name = "Field_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String fieldName;
    @XmlElement(name = "Old_Value", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String oldValue;
    @XmlElement(name = "New_Value", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String newValue;
    @XmlElement(name = "Audit_Creator", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String auditCreator;
    @XmlElement(name = "Audit_Created_Dt", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar auditCreatedDt;
    @XmlElement(name = "Author", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String author;
    @XmlElement(name = "Author_First_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String authorFirstName;
    @XmlElement(name = "Author_Last_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String authorLastName;
    @XmlElement(name = "Transaction_Complete_Dt", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar transactionCompleteDt;
    @XmlElement(name = "Amendment_Rider_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String amendmentRiderId;
    @XmlElement(name = "Agreement_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected BigInteger agreementId;
    @XmlElement(name = "Update_Reporting_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String updateReportingFlag;
    @XmlElement(name = "Reason_For_Change", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected String reasonForChange;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestId(BigInteger value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the alocRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlocRecordId() {
        return alocRecordId;
    }

    /**
     * Sets the value of the alocRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlocRecordId(String value) {
        this.alocRecordId = value;
    }

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldName(String value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the oldValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * Sets the value of the oldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldValue(String value) {
        this.oldValue = value;
    }

    /**
     * Gets the value of the newValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * Sets the value of the newValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewValue(String value) {
        this.newValue = value;
    }

    /**
     * Gets the value of the auditCreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditCreator() {
        return auditCreator;
    }

    /**
     * Sets the value of the auditCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditCreator(String value) {
        this.auditCreator = value;
    }

    /**
     * Gets the value of the auditCreatedDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getAuditCreatedDt() {
        return auditCreatedDt;
    }

    /**
     * Sets the value of the auditCreatedDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditCreatedDt(Calendar value) {
        this.auditCreatedDt = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the authorFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorFirstName() {
        return authorFirstName;
    }

    /**
     * Sets the value of the authorFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorFirstName(String value) {
        this.authorFirstName = value;
    }

    /**
     * Gets the value of the authorLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorLastName() {
        return authorLastName;
    }

    /**
     * Sets the value of the authorLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorLastName(String value) {
        this.authorLastName = value;
    }

    /**
     * Gets the value of the transactionCompleteDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getTransactionCompleteDt() {
        return transactionCompleteDt;
    }

    /**
     * Sets the value of the transactionCompleteDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCompleteDt(Calendar value) {
        this.transactionCompleteDt = value;
    }

    /**
     * Gets the value of the amendmentRiderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendmentRiderId() {
        return amendmentRiderId;
    }

    /**
     * Sets the value of the amendmentRiderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendmentRiderId(String value) {
        this.amendmentRiderId = value;
    }

    /**
     * Gets the value of the agreementId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgreementId() {
        return agreementId;
    }

    /**
     * Sets the value of the agreementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgreementId(BigInteger value) {
        this.agreementId = value;
    }

    /**
     * Gets the value of the updateReportingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateReportingFlag() {
        return updateReportingFlag;
    }

    /**
     * Sets the value of the updateReportingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateReportingFlag(String value) {
        this.updateReportingFlag = value;
    }

    /**
     * Gets the value of the reasonForChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonForChange() {
        return reasonForChange;
    }

    /**
     * Sets the value of the reasonForChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonForChange(String value) {
        this.reasonForChange = value;
    }

    public AuditLog withRequestId(BigInteger value) {
        setRequestId(value);
        return this;
    }

    public AuditLog withAlocRecordId(String value) {
        setAlocRecordId(value);
        return this;
    }

    public AuditLog withFieldName(String value) {
        setFieldName(value);
        return this;
    }

    public AuditLog withOldValue(String value) {
        setOldValue(value);
        return this;
    }

    public AuditLog withNewValue(String value) {
        setNewValue(value);
        return this;
    }

    public AuditLog withAuditCreator(String value) {
        setAuditCreator(value);
        return this;
    }

    public AuditLog withAuditCreatedDt(Calendar value) {
        setAuditCreatedDt(value);
        return this;
    }

    public AuditLog withAuthor(String value) {
        setAuthor(value);
        return this;
    }

    public AuditLog withAuthorFirstName(String value) {
        setAuthorFirstName(value);
        return this;
    }

    public AuditLog withAuthorLastName(String value) {
        setAuthorLastName(value);
        return this;
    }

    public AuditLog withTransactionCompleteDt(Calendar value) {
        setTransactionCompleteDt(value);
        return this;
    }

    public AuditLog withAmendmentRiderId(String value) {
        setAmendmentRiderId(value);
        return this;
    }

    public AuditLog withAgreementId(BigInteger value) {
        setAgreementId(value);
        return this;
    }

    public AuditLog withUpdateReportingFlag(String value) {
        setUpdateReportingFlag(value);
        return this;
    }

    public AuditLog withReasonForChange(String value) {
        setReasonForChange(value);
        return this;
    }

}
