//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BlockBusinessUnitCodeBankId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="BlockBusinessUnitCodeBankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blockBusinessUnitCodeBankId",
    "blockBusinessUnitCodeBankName"
})
@XmlRootElement(name = "BlockBusinessUnitCodeBank", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/Admin/BlockBusinessUnitCodeBank.xsd")
public class BlockBusinessUnitCodeBank
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "BlockBusinessUnitCodeBankId", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/Admin/BlockBusinessUnitCodeBank.xsd")
    protected Long blockBusinessUnitCodeBankId;
    @XmlElement(name = "BlockBusinessUnitCodeBankName", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/Admin/BlockBusinessUnitCodeBank.xsd")
    protected String blockBusinessUnitCodeBankName;

    /**
     * Gets the value of the blockBusinessUnitCodeBankId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBlockBusinessUnitCodeBankId() {
        return blockBusinessUnitCodeBankId;
    }

    /**
     * Sets the value of the blockBusinessUnitCodeBankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBlockBusinessUnitCodeBankId(Long value) {
        this.blockBusinessUnitCodeBankId = value;
    }

    /**
     * Gets the value of the blockBusinessUnitCodeBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockBusinessUnitCodeBankName() {
        return blockBusinessUnitCodeBankName;
    }

    /**
     * Sets the value of the blockBusinessUnitCodeBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockBusinessUnitCodeBankName(String value) {
        this.blockBusinessUnitCodeBankName = value;
    }

    public BlockBusinessUnitCodeBank withBlockBusinessUnitCodeBankId(Long value) {
        setBlockBusinessUnitCodeBankId(value);
        return this;
    }

    public BlockBusinessUnitCodeBank withBlockBusinessUnitCodeBankName(String value) {
        setBlockBusinessUnitCodeBankName(value);
        return this;
    }

}
