//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Group_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Group_id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Stage_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/DelegationApprovers.xsd}GroupApprover" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupName",
    "groupId",
    "stageName",
    "groupApprovers"
})
@XmlRootElement(name = "DelegationGroup", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DelegationApprovers.xsd")
public class DelegationGroup
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Group_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DelegationApprovers.xsd")
    protected String groupName;
    @XmlElement(name = "Group_id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DelegationApprovers.xsd")
    protected Integer groupId;
    @XmlElement(name = "Stage_Name", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DelegationApprovers.xsd")
    protected String stageName;
    @XmlElement(name = "GroupApprover", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/DelegationApprovers.xsd")
    protected List<GroupApprover> groupApprovers;

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupId(Integer value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the stageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * Sets the value of the stageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStageName(String value) {
        this.stageName = value;
    }

    /**
     * Gets the value of the groupApprovers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupApprovers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupApprovers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupApprover }
     * 
     * 
     */
    public List<GroupApprover> getGroupApprovers() {
        if (groupApprovers == null) {
            groupApprovers = new ArrayList<GroupApprover>();
        }
        return this.groupApprovers;
    }

    public DelegationGroup withGroupName(String value) {
        setGroupName(value);
        return this;
    }

    public DelegationGroup withGroupId(Integer value) {
        setGroupId(value);
        return this;
    }

    public DelegationGroup withStageName(String value) {
        setStageName(value);
        return this;
    }

    public DelegationGroup withGroupApprovers(GroupApprover... values) {
        if (values!= null) {
            for (GroupApprover value: values) {
                getGroupApprovers().add(value);
            }
        }
        return this;
    }

    public DelegationGroup withGroupApprovers(Collection<GroupApprover> values) {
        if (values!= null) {
            getGroupApprovers().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the groupApprovers property.
     * 
     * @param groupApprovers
     *     allowed object is
     *     {@link GroupApprover }
     *     
     */
    public void setGroupApprovers(List<GroupApprover> groupApprovers) {
        this.groupApprovers = groupApprovers;
    }

}
