//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd}Action_Taken_By" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Attribute_Changed" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actionTakenBies",
    "attributeChangeds"
})
@XmlRootElement(name = "DrawDown_Values", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
public class DrawDownValues
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Action_Taken_By", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected List<ActionTakenBy> actionTakenBies;
    @XmlElement(name = "Attribute_Changed", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/AuditLog.xsd")
    protected List<String> attributeChangeds;

    /**
     * Gets the value of the actionTakenBies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionTakenBies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionTakenBies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionTakenBy }
     * 
     * 
     */
    public List<ActionTakenBy> getActionTakenBies() {
        if (actionTakenBies == null) {
            actionTakenBies = new ArrayList<ActionTakenBy>();
        }
        return this.actionTakenBies;
    }

    /**
     * Gets the value of the attributeChangeds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeChangeds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeChangeds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAttributeChangeds() {
        if (attributeChangeds == null) {
            attributeChangeds = new ArrayList<String>();
        }
        return this.attributeChangeds;
    }

    public DrawDownValues withActionTakenBies(ActionTakenBy... values) {
        if (values!= null) {
            for (ActionTakenBy value: values) {
                getActionTakenBies().add(value);
            }
        }
        return this;
    }

    public DrawDownValues withActionTakenBies(Collection<ActionTakenBy> values) {
        if (values!= null) {
            getActionTakenBies().addAll(values);
        }
        return this;
    }

    public DrawDownValues withAttributeChangeds(String... values) {
        if (values!= null) {
            for (String value: values) {
                getAttributeChangeds().add(value);
            }
        }
        return this;
    }

    public DrawDownValues withAttributeChangeds(Collection<String> values) {
        if (values!= null) {
            getAttributeChangeds().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the actionTakenBies property.
     * 
     * @param actionTakenBies
     *     allowed object is
     *     {@link ActionTakenBy }
     *     
     */
    public void setActionTakenBies(List<ActionTakenBy> actionTakenBies) {
        this.actionTakenBies = actionTakenBies;
    }

    /**
     * Sets the value of the attributeChangeds property.
     * 
     * @param attributeChangeds
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeChangeds(List<String> attributeChangeds) {
        this.attributeChangeds = attributeChangeds;
    }

}
