//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.hydus.hwf.jaxb.adapters.XMLDatetimeAsCalendarAdapter;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Op_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Original_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Current_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Revised_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="US_Original_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="US_Current_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="US_Revised_Expiry_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Change_Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opCode",
    "originalExpiryDate",
    "currentExpiryDate",
    "revisedExpiryDate",
    "usOriginalExpiryDate",
    "usCurrentExpiryDate",
    "usRevisedExpiryDate",
    "changeFlag"
})
@XmlRootElement(name = "ExpiryDate", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd")
public class ExpiryDate
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Op_Code", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd")
    protected String opCode;
    @XmlElement(name = "Original_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar originalExpiryDate;
    @XmlElement(name = "Current_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar currentExpiryDate;
    @XmlElement(name = "Revised_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar revisedExpiryDate;
    @XmlElement(name = "US_Original_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar usOriginalExpiryDate;
    @XmlElement(name = "US_Current_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar usCurrentExpiryDate;
    @XmlElement(name = "US_Revised_Expiry_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar usRevisedExpiryDate;
    @XmlElement(name = "Change_Flag", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/ExpiryDate.xsd")
    protected String changeFlag;

    /**
     * Gets the value of the opCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the originalExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getOriginalExpiryDate() {
        return originalExpiryDate;
    }

    /**
     * Sets the value of the originalExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalExpiryDate(Calendar value) {
        this.originalExpiryDate = value;
    }

    /**
     * Gets the value of the currentExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getCurrentExpiryDate() {
        return currentExpiryDate;
    }

    /**
     * Sets the value of the currentExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentExpiryDate(Calendar value) {
        this.currentExpiryDate = value;
    }

    /**
     * Gets the value of the revisedExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getRevisedExpiryDate() {
        return revisedExpiryDate;
    }

    /**
     * Sets the value of the revisedExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisedExpiryDate(Calendar value) {
        this.revisedExpiryDate = value;
    }

    /**
     * Gets the value of the usOriginalExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getUSOriginalExpiryDate() {
        return usOriginalExpiryDate;
    }

    /**
     * Sets the value of the usOriginalExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSOriginalExpiryDate(Calendar value) {
        this.usOriginalExpiryDate = value;
    }

    /**
     * Gets the value of the usCurrentExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getUSCurrentExpiryDate() {
        return usCurrentExpiryDate;
    }

    /**
     * Sets the value of the usCurrentExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSCurrentExpiryDate(Calendar value) {
        this.usCurrentExpiryDate = value;
    }

    /**
     * Gets the value of the usRevisedExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getUSRevisedExpiryDate() {
        return usRevisedExpiryDate;
    }

    /**
     * Sets the value of the usRevisedExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSRevisedExpiryDate(Calendar value) {
        this.usRevisedExpiryDate = value;
    }

    /**
     * Gets the value of the changeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeFlag() {
        return changeFlag;
    }

    /**
     * Sets the value of the changeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeFlag(String value) {
        this.changeFlag = value;
    }

    public ExpiryDate withOpCode(String value) {
        setOpCode(value);
        return this;
    }

    public ExpiryDate withOriginalExpiryDate(Calendar value) {
        setOriginalExpiryDate(value);
        return this;
    }

    public ExpiryDate withCurrentExpiryDate(Calendar value) {
        setCurrentExpiryDate(value);
        return this;
    }

    public ExpiryDate withRevisedExpiryDate(Calendar value) {
        setRevisedExpiryDate(value);
        return this;
    }

    public ExpiryDate withUSOriginalExpiryDate(Calendar value) {
        setUSOriginalExpiryDate(value);
        return this;
    }

    public ExpiryDate withUSCurrentExpiryDate(Calendar value) {
        setUSCurrentExpiryDate(value);
        return this;
    }

    public ExpiryDate withUSRevisedExpiryDate(Calendar value) {
        setUSRevisedExpiryDate(value);
        return this;
    }

    public ExpiryDate withChangeFlag(String value) {
        setChangeFlag(value);
        return this;
    }

}
