//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.hydus.hwf.jaxb.adapters.XMLDatetimeAsCalendarAdapter;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd}Payment_Bank" minOccurs="0"/>
 *         &lt;element ref="{http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd}Payment_Id" minOccurs="0"/>
 *         &lt;element name="Payment_From_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Payment_To_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Payment_Currency_Cd" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentBank",
    "paymentId",
    "paymentFromDate",
    "paymentToDate",
    "paymentCurrencyCds"
})
@XmlRootElement(name = "SearchPaymentDetails", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd")
public class SearchPaymentDetails
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Payment_Bank", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd")
    protected String paymentBank;
    @XmlElement(name = "Payment_Id", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd")
    protected BigInteger paymentId;
    @XmlElement(name = "Payment_From_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar paymentFromDate;
    @XmlElement(name = "Payment_To_Date", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd", type = String.class)
    @XmlJavaTypeAdapter(XMLDatetimeAsCalendarAdapter.class)
    protected Calendar paymentToDate;
    @XmlElement(name = "Payment_Currency_Cd", namespace = "http://treasury.ge.com/schemas/ALOC/RequestDetails/SearchPaymentDetails.xsd")
    protected List<String> paymentCurrencyCds;

    /**
     * Gets the value of the paymentBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentBank() {
        return paymentBank;
    }

    /**
     * Sets the value of the paymentBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentBank(String value) {
        this.paymentBank = value;
    }

    /**
     * Gets the value of the paymentId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentId() {
        return paymentId;
    }

    /**
     * Sets the value of the paymentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentId(BigInteger value) {
        this.paymentId = value;
    }

    /**
     * Gets the value of the paymentFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPaymentFromDate() {
        return paymentFromDate;
    }

    /**
     * Sets the value of the paymentFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFromDate(Calendar value) {
        this.paymentFromDate = value;
    }

    /**
     * Gets the value of the paymentToDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPaymentToDate() {
        return paymentToDate;
    }

    /**
     * Sets the value of the paymentToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentToDate(Calendar value) {
        this.paymentToDate = value;
    }

    /**
     * Gets the value of the paymentCurrencyCds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentCurrencyCds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentCurrencyCds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPaymentCurrencyCds() {
        if (paymentCurrencyCds == null) {
            paymentCurrencyCds = new ArrayList<String>();
        }
        return this.paymentCurrencyCds;
    }

    public SearchPaymentDetails withPaymentBank(String value) {
        setPaymentBank(value);
        return this;
    }

    public SearchPaymentDetails withPaymentId(BigInteger value) {
        setPaymentId(value);
        return this;
    }

    public SearchPaymentDetails withPaymentFromDate(Calendar value) {
        setPaymentFromDate(value);
        return this;
    }

    public SearchPaymentDetails withPaymentToDate(Calendar value) {
        setPaymentToDate(value);
        return this;
    }

    public SearchPaymentDetails withPaymentCurrencyCds(String... values) {
        if (values!= null) {
            for (String value: values) {
                getPaymentCurrencyCds().add(value);
            }
        }
        return this;
    }

    public SearchPaymentDetails withPaymentCurrencyCds(Collection<String> values) {
        if (values!= null) {
            getPaymentCurrencyCds().addAll(values);
        }
        return this;
    }

    /**
     * Sets the value of the paymentCurrencyCds property.
     * 
     * @param paymentCurrencyCds
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCurrencyCds(List<String> paymentCurrencyCds) {
        this.paymentCurrencyCds = paymentCurrencyCds;
    }

}
