//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 01:19:41 PM IST 
//


package com.ge.aloc.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hydus.hwf.security.JAXBObjectSecureSerializer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="App_First_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="App_Last_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ssso_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Approver_Level_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appFirstName",
    "appLastName",
    "sssoId",
    "approverLevelId"
})
@XmlRootElement(name = "TreasuryGroupApprover", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/RequestDetails/TreasuryDelegationApprovers.xsd")
public class TreasuryGroupApprover
    extends JAXBObjectSecureSerializer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "App_First_Name", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/RequestDetails/TreasuryDelegationApprovers.xsd")
    protected String appFirstName;
    @XmlElement(name = "App_Last_Name", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/RequestDetails/TreasuryDelegationApprovers.xsd")
    protected String appLastName;
    @XmlElement(name = "Ssso_Id", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/RequestDetails/TreasuryDelegationApprovers.xsd")
    protected String sssoId;
    @XmlElement(name = "Approver_Level_Id", namespace = "http://www.tibco.com/schemas/ALOC/Resources/Schemas/RequestDetails/TreasuryDelegationApprovers.xsd")
    protected Integer approverLevelId;

    /**
     * Gets the value of the appFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppFirstName() {
        return appFirstName;
    }

    /**
     * Sets the value of the appFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppFirstName(String value) {
        this.appFirstName = value;
    }

    /**
     * Gets the value of the appLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppLastName() {
        return appLastName;
    }

    /**
     * Sets the value of the appLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppLastName(String value) {
        this.appLastName = value;
    }

    /**
     * Gets the value of the sssoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSssoId() {
        return sssoId;
    }

    /**
     * Sets the value of the sssoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSssoId(String value) {
        this.sssoId = value;
    }

    /**
     * Gets the value of the approverLevelId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getApproverLevelId() {
        return approverLevelId;
    }

    /**
     * Sets the value of the approverLevelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setApproverLevelId(Integer value) {
        this.approverLevelId = value;
    }

    public TreasuryGroupApprover withAppFirstName(String value) {
        setAppFirstName(value);
        return this;
    }

    public TreasuryGroupApprover withAppLastName(String value) {
        setAppLastName(value);
        return this;
    }

    public TreasuryGroupApprover withSssoId(String value) {
        setSssoId(value);
        return this;
    }

    public TreasuryGroupApprover withApproverLevelId(Integer value) {
        setApproverLevelId(value);
        return this;
    }

}
